### ISSUE TITLE
PlaidML with model.fit_generator() running slow

### ISSUE THREAD

**Issue by DanWertheimer** [plaidml/plaidml#197] opened 2018-11-08 12:15 UTC
I'm trying to replicate the code in [this notebook](https://github.com/DOsinga/deep_learning_cookbook/blob/master/04.2%20Build%20a%20recommender%20system%20based%20on%20outgoing%20Wikipedia%20links.ipynb)

However, when I run the line
`model.fit_generator(
    batchifier(pairs, positive_samples=positive_samples_per_batch, negative_ratio=10),
    epochs=15,
    steps_per_epoch=len(pairs) // positive_samples_per_batch,
    verbose=1
)`

My laptop slows down considerably and training is painfully slow. +-4 hours on GPU as compared to 30min on CPU. Every other training is fast and configured correctly.

Should be replicatable by cloning the repo and running the code with
 `
import plaidml.keras
plaidml.keras.install_backend()
`

at the beginning.

**Comment by brianretford** [comment] 2018-11-15 19:38
Sadly training anything with embeddings is very slow. We will try to address this in the nearish future, though we're a bit resource constrained right now.

This is a duplicate of #96

**Comment by brianretford** [comment] 2018-11-15 19:38
Duplicate of #96

**Closed by brianretford** 2018-11-15 19:38 UTC
