### ISSUE TITLE
Plaidml installation issue on windows

### ISSUE THREAD

**Issue by blipman35** [plaidml/plaidml#187] opened 2018-09-30 19:22 UTC
I am attempting to install plaidml on a windows 10 (home) pc with a gtx 1070 gpu. I've installed anaconda, which is working ok. Have tried multiple approaches but all giving the same error in plaidml-setup as follows: 

Traceback (most recent call last):
  File "c:\users\benli\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\benli\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\benli\Anaconda3\Scripts\plaidml-setup.exe\__main__.py", line 9, in <module>
  File "c:\users\benli\anaconda3\lib\site-packages\plaidml\plaidml_setup.py", line 44, in main
    devices, _ = plaidml.devices(ctx, limit=100, return_all=True)
  File "c:\users\benli\anaconda3\lib\site-packages\plaidml\__init__.py", line 1057, in devices
    enumerator = _Enumerator(ctx)
  File "c:\users\benli\anaconda3\lib\site-packages\plaidml\__init__.py", line 1016, in __init__
    ctx, ctypes.cast(None, _ENUM_DEVICES_FUNCTYPE), None)
OSError: exception: access violation reading 0x0000000000000010

Any advice? Thanks. (I'm a high school student so go easy pls!)

**Comment by brianretford** [comment] 2019-06-07 17:45
Hey if you're still interested, could you let us know if this reproduces with the latest version (sorry for the delay!)

**Comment by dgkutnic** [comment] 2019-06-14 17:18
Issues in the `needs info` state for 7+ days will be marked as obsolete and closed. If the issue is still occurring for you, please re-open the issue and provide us with the requested info.

**Closed by dgkutnic** 2019-06-14 17:18 UTC
Labels: obsolete
