### ISSUE TITLE
Any code fails to run throwing  TypeError: __init__() got an unexpected keyword argument 'threshold'

### ISSUE THREAD

**Issue by V-Kh** [plaidml/plaidml#224] opened 2019-01-12 19:18 UTC
Hi Folks
First of all, thank you for your work, now I finally can use my intel gpu. 
Now, the problem is that your basic example fails with the following error: 
```
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "opencl_intel_intel(r)_hd_graphics_haswell_gt2_mobile.0"
Traceback (most recent call last):
  File "1.py", line 16, in <module>
    model = kapp.VGG19()
  File "/usr/lib/python3.7/site-packages/keras/applications/__init__.py", line 28, in wrapper
    return base_fun(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/keras/applications/vgg19.py", line 11, in VGG19
    return vgg19.VGG19(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/keras_applications/vgg19.py", line 112, in VGG19
    name='block1_conv1')(img_input)
  File "/usr/lib/python3.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/lib/python3.7/site-packages/keras/layers/convolutional.py", line 188, in call
    return self.activation(outputs)
  File "/usr/lib/python3.7/site-packages/keras/activations.py", line 130, in relu
    return K.relu(x, alpha=alpha, max_value=max_value, threshold=threshold)
  File "/usr/lib/python3.7/site-packages/plaidml/tile.py", line 255, in function
    operation = cls(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'threshold'
```
I tried both CPU & GPU and get the same results. 
UPD. I also tried various examples with the same result. Any ides so far?

**Comment by Luux** [comment] 2019-01-25 12:46
Same problem here. Trying to get keras-tcn running through plaidml. Output:
`File "[xxxxxxxxx]\classifier.py", line 75, in build_model
    tcn_layer1 = TCN(return_sequences=False, nb_stacks=4, dilations=[1, 2, 4, 8, 16, 32], padding="causal")(input_layer)
  File "C:\Users\Luux\Miniconda3\lib\site-packages\tcn\tcn.py", line 165, in __call__
    self.kernel_size, self.padding, self.dropout_rate, name=self.name)
  File "C:\Users\Luux\Miniconda3\lib\site-packages\tcn\tcn.py", line 72, in residual_block
    x = Activation('relu')(conv)
  File "C:\Users\Luux\Miniconda3\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\Luux\Miniconda3\lib\site-packages\keras\layers\core.py", line 299, in call
    return self.activation(inputs)
  File "C:\Users\Luux\Miniconda3\lib\site-packages\keras\activations.py", line 130, in relu
    return K.relu(x, alpha=alpha, max_value=max_value, threshold=threshold)
  File "C:\Users\Luux\Miniconda3\lib\site-packages\plaidml\tile.py", line 255, in function
    operation = cls(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'threshold'`

**Comment by tzerrell** [comment] 2019-02-01 19:08
This is related to https://github.com/plaidml/plaidml/issues/201 and should be fixed in 0.5.0. Let us know if the problem persists

**Comment by V-Kh** [comment] 2019-02-01 19:16
@tzerrell Thanks! When do you plan to release it?

**Comment by gbrow004** [comment] 2019-02-01 20:31
I upgraded PlaidML to 0.50 but still get the same error, regardless of GPU or Python version.

**Comment by brianretford** [comment] 2019-02-01 20:46
did you update plaidml-keras also?

**Comment by gbrow004** [comment] 2019-02-01 20:55
Yes, I did the pip --user --upgrade plaidml-keras thing. (for both python 3 and 2).

I either get this error or the PlaidML backend doesn't support tensor shapes with set_value.

**Comment by V-Kh** [comment] 2019-02-04 16:13
@tzerrell @brianretford I see that 0.5.0 PR hasn't been merged yet. Any plans?

**Comment by brianretford** [comment] 2019-02-04 19:40
Yup, will happen today

Sent from my iPhone

On Feb 4, 2019, at 8:14 AM, V-Kh <notifications@github.com<mailto:notifications@github.com>> wrote:


@tzerrell<https://github.com/tzerrell> @brianretford<https://github.com/brianretford> I see that 0.5.0 PR hasn't been merged yet. Any plans?

**Comment by brianretford** [comment] 2019-02-05 03:37
Let me know if the issue is resolved!

**Comment by I-himawari** [comment] 2019-02-05 05:20
Thank you to update! this issue is resolved, but I found other issue.

Traceback (most recent call last):
  File "audio_tcn.py", line 73, in <module>
    run_task()
  File "audio_tcn.py", line 36, in run_task
    use_skip_connections=True
  File "C:\Users\preta774\Anaconda3\envs\k2\lib\site-packages\tcn\tcn.py", line 242, in compiled_tcn
    model.compile(adam, loss='sparse_categorical_crossentropy', metrics=[accuracy])
  File "C:\Users\preta774\Anaconda3\envs\k2\lib\site-packages\keras\engine\training.py", line 451, in compile
    handle_metrics(output_metrics)
  File "C:\Users\preta774\Anaconda3\envs\k2\lib\site-packages\keras\engine\training.py", line 420, in handle_metrics
    mask=masks[i])
  File "C:\Users\preta774\Anaconda3\envs\k2\lib\site-packages\keras\engine\training_utils.py", line 404, in weighted
    score_array = fn(y_true, y_pred)
  File "C:\Users\preta774\Anaconda3\envs\k2\lib\site-packages\tcn\tcn.py", line 235, in accuracy
    y_true = K.squeeze(y_true, -1)
  File "C:\Users\preta774\Anaconda3\envs\k2\lib\site-packages\plaidml\keras\backend.py", line 1539, in squeeze
    raise ValueError('Can only squeeze length 1 axis')
ValueError: Can only squeeze length 1 axis

and SpatialDropoutDropout1D is not exits.

**Comment by brianretford** [comment] 2019-05-31 17:30
That's a separate issue but @SleepProgger did add spatial dropout support in 0.6.0

**Closed by brianretford** 2019-05-31 17:30 UTC
