### ISSUE TITLE
NotImplementedError: rnn is not implemented for variable sized inputs

### ISSUE THREAD

**Issue by crowoy** [plaidml/plaidml#200] opened 2018-11-15 16:07 UTC
Recently attempted to start using PlaidML, instead of just using Keras (w/ Tensorflow), as I have an AMD GPU on my MacBook Pro which would be great to start utilising. I'm trying to train an LSTM, but I'm running into some issues.

All code worked perfectly until I added the following 2 lines:
```
import plaidml.keras
plaidml.keras.install_backend()
```

I've also tried: `os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"`

Both of these options produce this trace (whether I select the GPU with OpenCL or Metal):

```
(env) $ python run.py
xxx/dev/scripts/model.py:28: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  model.add(LSTM(input_dim=neurons_input, output_dim=layer_size, return_sequences=True))
xxx/dev/scripts/model.py:28: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(units=50, return_sequences=True, input_shape=(None, 120...)`
  model.add(LSTM(input_dim=neurons_input, output_dim=layer_size, return_sequences=True))
INFO:plaidml:Opening device "metal_amd_radeon_pro_560x.0"
Traceback (most recent call last):
  File "run.py", line 81, in <module>
    model = m.build_model(xs_norm.shape[2]-1, num_neurons, learning_rate)
  File "xxx/dev/scripts/model.py", line 28, in build_model
    model.add(LSTM(input_dim=neurons_input, output_dim=layer_size, return_sequences=True))
  File "xxx/envs/env/lib/python2.7/site-packages/keras/engine/sequential.py", line 164, in add
    layer(x)
  File "xxx/envs/env/lib/python2.7/site-packages/keras/layers/recurrent.py", line 500, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "xxx/envs/env/lib/python2.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "xxx/envs/env/lib/python2.7/site-packages/keras/layers/recurrent.py", line 2112, in call
    initial_state=initial_state)
  File "xxx/envs/env/lib/python2.7/site-packages/keras/layers/recurrent.py", line 609, in call
    input_length=timesteps)
  File "xxx/envs/env/lib/python2.7/site-packages/plaidml/keras/backend.py", line 1330, in rnn
    raise NotImplementedError('rnn is not implemented for variable sized inputs')
NotImplementedError: rnn is not implemented for variable sized inputs
```

**Comment by brianretford** [comment] 2018-11-15 17:53
Duplicate of #142

**Closed by brianretford** 2018-11-15 17:53 UTC
