### ISSUE TITLE
CNN different results with GPU and CPU

### ISSUE THREAD

**Issue by nikifaets** [plaidml/plaidml#192] opened 2018-10-17 18:53 UTC
Before going into details, I want to spend a moment to thank you for allowing us to use deep learning on AMD GPUs!

I use the following system:

OS: Antergos Linux
Interface: Keras
GPU: AMD Radeon R9 280
GPU driver: amdgpu (it is not very stable with this GPU. However, radeon, the stable one, does not support newer OpenCL)
CPU: intel i3-4330

So, when I ran my project on the AMD GPU I got some messy output. 
It is an autoencoder, the upper row is the output, the second row is the original input. 
with CPU: https://ibb.co/dzNuaf
with GPU: https://ibb.co/jhamo0 

Network: https://pastebin.com/f6fV35S0. This is an example one, but all I have used end up with this odd output. 
Also, a couple of times, the sigmoid activation function gave output more the 1.

**Comment by brianretford** [comment] 2018-11-15 19:43
I think the ROCm driver stack now supports most linux distros, it might help? We have indeed not had great luck with the amdgpu drivers and last I checked they were quite out of date. Apologies for the delay in responding

**Comment by brianretford** [comment] 2019-06-14 17:30
Can you attempt to reproduce in 0.6.0? We've made several fixes that might have resolved this.

**Comment by dgkutnic** [comment] 2019-06-21 20:53
Issues in the `needs info` state for 7+ days will be marked as obsolete and closed. If the issue is still occurring for you, please re-open the issue and provide us with the requested info.

**Closed by dgkutnic** 2019-06-21 20:53 UTC
Labels: needs info, obsolete
