### ISSUE TITLE
plaidml-setup fails with Intel Iris Graphics 6100

### ISSUE THREAD

**Issue by florian-koenig** [plaidml/plaidml#210] opened 2018-12-10 11:08 UTC
Hi,

I followed the installation instructions on my early 2015 MacBook Pro (13-inch Retina) with an Intel Iris Graphics 6100 GPU (1.5 GB):

```
foo:~ foo$ mkvirtualenv plaidml -p python3
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/foo/.virtualenvs/plaidml/bin/python3.6
Also creating executable in /Users/foo/.virtualenvs/plaidml/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/foo/.virtualenvs/plaidml/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/foo/.virtualenvs/plaidml/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/foo/.virtualenvs/plaidml/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/foo/.virtualenvs/plaidml/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/foo/.virtualenvs/plaidml/bin/get_env_details

(plaidml) foo:~ foo$ pip install -U plaidml-keras
Collecting plaidml-keras
  Using cached https://files.pythonhosted.org/packages/97/39/f53511f15c71280449bb01e2f7825e90c1e42d4ff2e5b1afedef82b926d9/plaidml_keras-0.3.5-py2.py3-none-any.whl
Collecting plaidml (from plaidml-keras)
  Using cached https://files.pythonhosted.org/packages/a8/7e/d9f8280a035434132b3c9463c05dfe0150e4b10ca5c2a94a642683d18c90/plaidml-0.3.5-py2.py3-none-macosx_10_10_x86_64.whl
Collecting keras==2.2.2 (from plaidml-keras)
  Using cached https://files.pythonhosted.org/packages/34/7d/b1dedde8af99bd82f20ed7e9697aac0597de3049b1f786aa2aac3b9bd4da/Keras-2.2.2-py2.py3-none-any.whl
Collecting six (from plaidml-keras)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting enum34>=1.1.6 (from plaidml->plaidml-keras)
  Using cached https://files.pythonhosted.org/packages/af/42/cb9355df32c69b553e72a2e28daee25d1611d2c0d9c272aa1d34204205b2/enum34-1.1.6-py3-none-any.whl
Collecting numpy (from plaidml->plaidml-keras)
  Using cached https://files.pythonhosted.org/packages/74/68/2b00ba3c7390354db2a1706291750b6b7e911f6f79c0bd2184ae04f3c6fd/numpy-1.15.4-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting requests (from plaidml->plaidml-keras)
  Using cached https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl
Collecting keras-preprocessing==1.0.2 (from keras==2.2.2->plaidml-keras)
  Using cached https://files.pythonhosted.org/packages/71/26/1e778ebd737032749824d5cba7dbd3b0cf9234b87ab5ec79f5f0403ca7e9/Keras_Preprocessing-1.0.2-py2.py3-none-any.whl
Collecting h5py (from keras==2.2.2->plaidml-keras)
  Using cached https://files.pythonhosted.org/packages/44/81/50a0560aac57a33c2a624d9e160735f39d7a6324e3f6f115425a1bf01dd9/h5py-2.8.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting keras-applications==1.0.4 (from keras==2.2.2->plaidml-keras)
  Using cached https://files.pythonhosted.org/packages/54/90/8f327deaa37a71caddb59b7b4aaa9d4b3e90c0e76f8c2d1572005278ddc5/Keras_Applications-1.0.4-py2.py3-none-any.whl
Collecting pyyaml (from keras==2.2.2->plaidml-keras)
Collecting scipy>=0.14 (from keras==2.2.2->plaidml-keras)
  Using cached https://files.pythonhosted.org/packages/a0/b6/70bf61c1badb5fea82d4c558e05e76c2dee5e77bb072fe465d7c7a87287d/scipy-1.1.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting idna<2.8,>=2.5 (from requests->plaidml->plaidml-keras)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->plaidml->plaidml-keras)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests->plaidml->plaidml-keras)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->plaidml->plaidml-keras)
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Installing collected packages: enum34, six, numpy, idna, chardet, urllib3, certifi, requests, plaidml, scipy, keras-preprocessing, h5py, keras-applications, pyyaml, keras, plaidml-keras
Successfully installed certifi-2018.11.29 chardet-3.0.4 enum34-1.1.6 h5py-2.8.0 idna-2.7 keras-2.2.2 keras-applications-1.0.4 keras-preprocessing-1.0.2 numpy-1.15.4 plaidml-0.3.5 plaidml-keras-0.3.5 pyyaml-3.13 requests-2.20.1 scipy-1.1.0 six-1.12.0 urllib3-1.24.1
```

Unfortunately, `plaidml-setup` fails with the following output:
```
PlaidML Setup (0.3.5)

Thanks for using PlaidML!

Some Notes:
  * Bugs and other issues: https://github.com/plaidml/plaidml
  * Questions: https://stackoverflow.com/questions/tagged/plaidml
  * Say hello: https://groups.google.com/forum/#!forum/plaidml-dev
  * PlaidML is licensed under the GNU AGPLv3
 
2018-12-10 09:59:35.817 python3.6[26570:1676508] -[MTLIGAccelDevice recommendedMaxWorkingSetSize]: unrecognized selector sent to instance 0x7fb895143c00
Traceback (most recent call last):
  File "/Users/foo/.virtualenvs/dl/bin/plaidml-setup", line 11, in <module>
    sys.exit(main())
  File "/Users/foo/.virtualenvs/dl/lib/python3.6/site-packages/plaidml/plaidml_setup.py", line 44, in main
    devices, _ = plaidml.devices(ctx, limit=100, return_all=True)
  File "/Users/foo/.virtualenvs/dl/lib/python3.6/site-packages/plaidml/__init__.py", line 1057, in devices
    enumerator = _Enumerator(ctx)
  File "/Users/foo/.virtualenvs/dl/lib/python3.6/site-packages/plaidml/__init__.py", line 1016, in __init__
    ctx, ctypes.cast(None, _ENUM_DEVICES_FUNCTYPE), None)
  File "/Users/foo/.virtualenvs/dl/lib/python3.6/site-packages/plaidml/__init__.py", line 716, in _check_err
    self.raise_last_status()
  File "/Users/foo/.virtualenvs/dl/lib/python3.6/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Internal: The exception chain appears to be corrupt
```

I can't find anything related to this error on the web. Any ideas?

**Comment by minhlab** [comment] 2019-03-15 20:53
I also have a MacBook Pro (13-inch Retina) but from 2014. When running plaidml-setup, I got this error:

```
OSError: dlopen(/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/libplaidml.dylib, 6): image not found
```

**Comment by quocdat32461997** [comment] 2019-04-13 16:40
I have a MacPro 2018. Everything works except plaidml-setup gives me error that "image not found"

**Comment by quocdat32461997** [comment] 2019-04-13 16:58
@minhlab Try to create a separate virtualenv and installed plaidml there. It works for me

**Comment by minhlab** [comment] 2019-04-13 23:14
Thanks, that worked!

**Comment by brianretford** [comment] 2019-06-07 17:24
@florian-koenig sorry for the delay, if you're interested in trying the latest version and letting us know if it works that would be great. Generally metal works the best on macOS

**Comment by dgkutnic** [comment] 2019-06-14 17:14
Issues in the `needs info` state for 7+ days will be marked as obsolete and closed. If the issue is still occurring for you, please re-open the issue and provide us with the requested info.

**Closed by dgkutnic** 2019-06-14 17:14 UTC
Labels: needs info, obsolete
