### ISSUE TITLE
Using multiple GPUs ?

### ISSUE THREAD

**Issue by fmichaud** [plaidml/plaidml#191] opened 2018-10-11 21:35 UTC
Hello,

First, thank you for this great project ! I can finally process data with Keras using an AMD GPU...
Is it possible to use multiple GPUs during computing data ?

Regards from France,

**Comment by brianretford** [comment] 2018-10-12 23:43
Hey François,

Currently PlaidML doesn’t support multi-gpu configurations. We are currently working on a very core refactoring of how we generate code that will enable multi-gpu support. We hope to start publishing public roadmaps and more information on the new system soon.

**Comment by SolankiAnand** [comment] 2019-02-10 04:58
Do we have any update on this?

**Comment by brianretford** [comment] 2019-02-11 15:32
We've completed the refactorings that we wanted to, yes. We're working on porting all of PlaidML to work on top of the new system, at which point adding multi-gpu support should straightforward.

**Comment by SolankiAnand** [comment] 2019-02-11 16:24
@brianretford great, thank you! Could you please share the approximate timeline?

**Comment by brianretford** [comment] 2019-02-12 18:44
We're hoping to have a prototype GPU stripe-backend out in 0.6, at which point multi-GPU support is pending hiring on the Intel side (underway) or a community member deciding to implement it :-)

**Comment by ClassyNinjaPirate** [comment] 2019-02-24 05:34
Hello,
forgive me, but I don't understand  what "We're hoping to have a prototype GPU stripe-backend out in 0.6" means. When is it expected? 
sorry and thanks again.

**Comment by asheetal** [comment] 2019-03-18 11:32
Hoping to see multi-gpu support on plaidml soon

**Comment by aviallon** [comment] 2019-04-24 21:33
Hello,
is it already there ? I didn't find anything related to that in the docs.
Thanks for the good work anyway.

**Comment by gbrow004** [comment] 2019-05-08 17:01
Will there be a limit on the number of GPU's that PlaidML will be able to use? Assuming the hardware side of things is setup properly, of course.

**Comment by brianretford** [comment] 2019-05-08 17:44
Well, there might be a productive limit for a particular problem, but technically there probably won't be limits? To catch up with the questions above, the new backend will not inherently support multi-GPU but will make doing so more feasible. I imagine it will still be an intensive project, one that we haven't started yet but would like to start when we have resources available.

**Comment by aviallon** [comment] 2019-05-08 18:40
That would be very nice :)

**Comment by brianretford** [comment] 2019-06-07 17:26
Duplicate of #32

**Closed by brianretford** 2019-06-07 17:26 UTC
Labels: help wanted
