### ISSUE TITLE
Cannot use custom activation function (SineReLU) from Keras-Contrib

### ISSUE THREAD

**Issue by wilderrodrigues** [plaidml/plaidml#222] opened 2019-01-09 11:47 UTC
Hi,

I have been using Keras + TensorFlow for more than 2 years now. It is a good combination, except when one needs to try out quick experiments on a MacBook and it doesn't use the AMD Radeon GPUs. Hence, kudos for your work on PlaidML, which I discover a couple of weeks ago.

I'm currently using PlaidML + Keras to train custom models, using CNNs, LSTMs and GRUs architectures. All works fine. However, when trying to use the SineReLU, a custom activation function that is part of Keras Contrib, it unfortunately breaks. Based on the error message, it seems that the `DerivDefines` is not able to compute the `sin` function, which is used by the SineReLU. 

I traced the error back to this code snippet in the `symbolic.cc` file:

```
  auto it = DerivDefines.find(op->fn());
  if (it == DerivDefines.end()) {
    throw std::runtime_error("Invalid derivative: unknown function " + op->fn());
  }
```

And the unknown function is the `sin` function, as I mentioned above.

How hard would be to get it implemented? Keras Contrib contains many other implementations that would depend on sin/cos functions.

Looking forward to hear from you and if help is needed, please let me know.

Cheers,
Wilder

**Comment by wilderrodrigues** [comment] 2019-01-09 11:55
Just checking further in the source code, I saw that the function is actually defined under`builtins.cc`:

```
    {"cos", ddef({"-sin(X1) * DY"})},
    {"cosh", ddef({"sinh(X1) * DY"})},
    {"sin", ddef({"cos(X1) * DY"})},
    {"sinh", ddef({"cosh(X1) * DY"})},
```

I will inspect further and try to understand why it can't be found.

**Comment by brianretford** [comment] 2019-05-31 17:34
Catching up on our backlog here, can you provide a concise reproduction?

**Comment by dgkutnic** [comment] 2019-06-07 17:31
Issues in the `needs info` state for 7+ days will be marked as obsolete and closed. If the issue is still occurring for you, please re-open the issue and provide us with the requested info.

**Closed by dgkutnic** 2019-06-07 17:31 UTC
Labels: needs info, obsolete
