### ISSUE TITLE
GPU is not being utilized (RX 570)

### ISSUE THREAD

**Issue by hardworker27** [plaidml/plaidml#312] opened 2019-05-19 01:10 UTC
Hello,
Thank you very much for building this plaidml.
I set up then I got
"Multiple devices detected (You can override by setting PLAIDML_DEVICE_IDS).
Please choose a default device:

   1 : opencl_amd_ellesmere.0
   2 : opencl_amd_ellesmere.1

Default device? (1,2)[1]:2

Selected device:
    opencl_amd_ellesmere.1

Almost done. Multiplying some matrices...
Tile code:
  function (B[X,Z], C[Z,Y]) -> (A) { A[x,y : X,Y] = +(B[x,z] * C[z,y]); }
Whew. That worked.
Save settings to C:\Users\XXXXX\.plaidml? (y,n)[y]:y"

and tested with 
plaidbench keras mobilenet
"Running 1024 examples with mobilenet, batch size 1, on backend plaid
INFO:plaidml:Opening device "opencl_amd_ellesmere.1"
Model loaded.
Compiling network... Warming up... Running...
Example finished, elapsed: 3.404s (compile), 5.015s (execution)
keras opencl_amd_ellesmere.1
-----------------------------------------------------------------------------------------
Network Name         Inference Latency         Time / FPS
-----------------------------------------------------------------------------------------
mobilenet            4.90 ms                   1.49 ms / 669.74 fps
Correctness: PASS, max_error: 1.8053706298815086e-05, max_abs_error: 9.760260581970215e-07, fail_ratio: 0.0"

But when I was playing with my jupyter notebook, I was testing with this one: https://github.com/lazyprogrammer/machine_learning_examples/blob/master/nlp_class3/lstm_toxic.py . Then both of my GPUs are 0-2% utilization only. The training was extremely low.

Here is my clinfo:
Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1 AMD-APP (2841.5)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices
  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               2
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    Radeon RX 570 Series
  Device Topology:                               PCI[ B#1, D#0, F#0 ]
  Max compute units:                             32
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           1024
  Max work group size:                           256
  Preferred vector width char:                   4
  Preferred vector width short:                  2
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      4
  Native vector width short:                     2
  Native vector width int:                       1
  Native vector width long:                      1
  Native vector width float:                     1
  Native vector width double:                    1
  Max clock frequency:                           1244Mhz
  Address bits:                                  64
  Max memory allocation:                         3422552064
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          64
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   1024
  Alignment (bits) of base address:              2048
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     No
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    16384
  Global memory size:                            4294967296
  Constant buffer size:                          3422552064
  Max number of constant args:                   8
  Local memory type:                             Scratchpad
  Local memory size:                             32768
  Max pipe arguments:                            16
  Max pipe active reservations:                  16
  Max pipe packet size:                          3422552064
  Max global variable size:                      3080296704
  Max global variable preferred total size:      4294967296
  Max read/write image args:                     64
  Max on device events:                          1024
  Queue on device max size:                      8388608
  Max on device queues:                          1
  Queue on device preferred size:                262144
  SVM capabilities:
    Coarse grain buffer:                         Yes
    Fine grain buffer:                           Yes
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     64
  Error correction support:                      0
  Unified memory for Host and Device:            0
  Profiling timer resolution:                    1
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     No
  Queue on Host properties:
    Out-of-Order:                                No
    Profiling :                                  Yes
  Queue on Device properties:
    Out-of-Order:                                Yes
    Profiling :                                  Yes
  Platform ID:                                   00007FFC55131FD0
  Name:                                          Ellesmere
  Vendor:                                        Advanced Micro Devices, Inc.
  Device OpenCL C version:                       OpenCL C 2.0
  Driver version:                                2841.5
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 2.0 AMD-APP (2841.5)
  Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_liquid_flash cl_amd_planar_yuv

**Comment by SleepProgger** [comment] 2019-05-19 02:59
Are you sure you used the plaidml backend ?
You can test this by printing `keras.backend.backend()`

Selecting the plaidml backend for keras can be done by setting the environment variable `KERAS_BACKEND` to `plaidml.keras.backend`

**Comment by hardworker27** [comment] 2019-05-19 03:16
Thank you.
Yes, I used the plaidml backend, I just checked it. At beginning I used:
import plaidml.keras
plaidml.keras.install_backend()

**Comment by hardworker27** [comment] 2019-05-19 03:55
I also want to add that: when I did the plaidbench test, the assigned GPU utilization went up to 100% for a moment which I think it worked as it's supposed to. 
I still have problem with the script at the top. The utilization still ~0% during fitting.
Thank you a lot.

**Comment by SleepProgger** [comment] 2019-05-19 18:45
Sorry can't really help then (not going to give kaggle my phone #).
GPU utilization shown by different tools is not always the really relevant info for this kind of thing tho.

**Comment by hardworker27** [comment] 2019-05-20 03:23
Thank you. OK, not looking at the GPU utilization shown by windows, I tested with another script using CNN and it was very slow too. Sometimes it froze for a while and then continued. 
I will test it with ubuntu though.

**Comment by brianretford** [comment] 2019-05-20 20:16
Training LSTMs is slow right now due to embedding performance. We are hoping to have a more portable and efficient approach designed for this soon. This is probably a duplicate of #171 .

**Closed by brianretford** 2019-05-20 20:16 UTC
