### ISSUE TITLE
[macOS] model.fit() loss: nan

### ISSUE THREAD

**Issue by andyoneal** [plaidml/plaidml#26] opened 2017-10-22 22:36 UTC
Ran mnist_cnn.py from keras/examples after adding plaidml as the backend. This issue affects many others, but this is the simplest example.

Will run fine for a while, then loss will hit nan and acc will plummet until it hits 0, where it stays.

> Andys-iMac-2:examples andy$ python mnist_cnn.py 
> x_train shape: (60000, 28, 28, 1)
> 60000 train samples
> 10000 test samples
> INFO:plaidml:Opening device "amd_radeon_pro_580_compute_engine.0
> Train on 60000 samples, validate on 10000 samples
> Epoch 1/12
> 59776/60000 [============================>.] - ETA: 0s - loss: 0.3177 - acc: 0.9025INFO:plaidml:Analyzing Ops: 85 of 285 operations complete
> 60000/60000 [==============================] - 27s - loss: 0.3172 - acc: 0.9026 - val_loss: 0.2699 - val_acc: 0.9217
> Epoch 2/12
> 60000/60000 [==============================] - 18s - loss: 0.1104 - acc: 0.9666 - val_loss: 0.2247 - val_acc: 0.9308
> Epoch 3/12
> 60000/60000 [==============================] - 19s - loss: nan - acc: 0.5408 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 4/12
> 60000/60000 [==============================] - 19s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 5/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 6/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 7/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 8/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 9/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 10/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 11/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 12/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Test loss: nan
> Test accuracy: 0.0

**Comment by choongng** [comment] 2017-10-22 23:53
Thanks Andy, we've seen issues on Mac as well and are working on tracking them down. Once we get that all ironed out we'll mark Mac "supported" and ship a new release with binaries.

**Comment by choongng** [comment] 2017-10-23 00:20
The author of this tutorial also appears to be seeing a correctness issue: https://qiita.com/croquette0212/items/cae15761876e1e937a6c

**Comment by jbruestle** [comment] 2017-10-23 21:29
@andyoneal, I can't seem to reproduce the error after a system update.  Is the nan error consistently reproducible or intermittent?  Also, what version of OS X and Xcode are you using?  Finally, it case it is Xcode version related, I've attached some pips I built internally (that don't have the issue on any systems I've tested on).  Could you try these pips and see if it fixes the problem?

https://storage.googleapis.com/vertexai-releases/git-issue-26/plaidml_keras-0.0.0.dev0-py2-none-any.whl
https://storage.googleapis.com/vertexai-releases/git-issue-26/plaidml-0.0.0.dev0-py2-none-macosx_10_10_x86_64.whl

**Comment by andyoneal** [comment] 2017-10-24 03:00
> Andys-iMac-2:examples andy$ python mnist_cnn.py 
> x_train shape: (60000, 28, 28, 1)
> 60000 train samples
> 10000 test samples
> INFO:plaidml:Opening device "amd_radeon_pro_580_compute_engine.0
> Train on 60000 samples, validate on 10000 samples
> Epoch 1/12
> 59776/60000 [============================>.] - ETA: 0s - loss: 0.3356 - acc: 0.8967INFO:plaidml:Analyzing Ops: 85 of 285 operations complete
> 60000/60000 [==============================] - 21s - loss: 0.3350 - acc: 0.8969 - val_loss: 0.2891 - val_acc: 0.9117
> Epoch 2/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.6518 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 3/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 4/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 5/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 6/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 7/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 8/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 9/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 10/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 11/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 12/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Test loss: nan
> Test accuracy: 0.0

Uninstalled plaidml and plaidml-keras via pip, reinstalled using the wheels you linked. No change.

Using High Sierra 10.13.0. "/usr/bin/xcodebuild -version" says Xcode 9.0 Build version 9A235.

**Comment by jbruestle** [comment] 2017-10-24 03:40
Thanks for much for the additional testing!  At this point, since you used the same pips as me, we can rule out anything related to build process.  I've been testing primarily on 10.12.6, I'll see if I can repro on 10.13.0 and get back to you.

**Comment by flaub** [comment] 2017-10-24 05:24
Using the wheels from @jbruestle posted above, I was able to get this to work on my older iMac with an NVIDIA GPU:
```
(plaidml) imac:examples flaub$ python mnist_cnn.py
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
INFO:plaidml:Opening device "geforce_gtx_680mx.0
Train on 60000 samples, validate on 10000 samples
Epoch 1/12
ERROR:plaidml:OpenCL: OpenCL Build Warning : Compiler build log: (cb=12)
59904/60000 [============================>.] - ETA: 0s - loss: 0.3302 - acc: 0.9002ERROR:plaidml:OpenCL: OpenCL Build Warning : Compiler build log: (cb=12)
60000/60000 [==============================] - 97s - loss: 0.3298 - acc: 0.9003 - val_loss: 0.0792 - val_acc: 0.9746
Epoch 2/12
60000/60000 [==============================] - 89s - loss: 0.1138 - acc: 0.9663 - val_loss: 0.0548 - val_acc: 0.9834
Epoch 3/12
60000/60000 [==============================] - 89s - loss: 0.0858 - acc: 0.9745 - val_loss: 0.0435 - val_acc: 0.9862
Epoch 4/12
...
60000/60000 [==============================] - 219s - loss: 0.0368 - acc: 0.9893 - val_loss: 0.0274 - val_acc: 0.9909
Test loss: 0.0273694936991
Test accuracy: 0.9909
```

**Comment by choongng** [comment] 2017-10-24 06:44
Tested working on Late 2016 MacBook Pro 15 (Radeon Pro 460):

[plaid log.txt](https://github.com/plaidml/plaidml/files/1409791/plaid.log.txt)

**Comment by flaub** [comment] 2017-10-24 06:58
@jbruestle I wonder what this is all about:
```
ERROR:plaidml:OpenCL: OpenCL Build Warning : Compiler build log: (cb=12)
```

I can turn on higher logging to see if I can get more info.

**Comment by jbruestle** [comment] 2017-10-24 16:16
@andyoneal Can you clin

**Comment by andyoneal** [comment] 2017-10-24 16:22
typo?

**Comment by jbruestle** [comment] 2017-10-24 16:40
Whoops, not sure what happened there, I thing I switched windows midstream, also, didn't mean to close!

**Comment by jbruestle** [comment] 2017-10-25 23:20
Ok, managed to reproduce and fix a similar race condition bug here which I think may have been responsible.  Here are new pips to try, uninstall the old ones, install these, and see if the problem still occurs.

https://storage.googleapis.com/vertexai-releases/git-issue-26-part2/plaidml_keras-0.0.0.dev0-py2-none-any.whl
https://storage.googleapis.com/vertexai-releases/git-issue-26-part2/plaidml-0.0.0.dev0-py2-none-macosx_10_10_x86_64.whl

Thanks again!

**Comment by jbruestle** [comment] 2017-10-27 20:34
@andyoneal At this point, the likely fix is in our release, so you should be able to install is just via pip install plaidml.

**Comment by yokoe** [comment] 2017-10-28 06:55
Hi, I am the author of that post ( https://qiita.com/croquette0212/items/cae15761876e1e937a6c ).
I tried the new pips (plaidml (0.1.1) and plaidml-keras (0.1.1)) but unfortunately the problem still occurs on my iMac.

**Comment by jbruestle** [comment] 2017-10-28 16:29
Thanks for commenting.  I believe this issue may be related to issue #47 as well.  I have a good repro for that issue, so once I fix it, I'll add a comment here as well.

**Comment by andyoneal** [comment] 2017-10-28 18:22
No luck for me either. Something slightly new though. Ran mnist_cnn.py again, interrupted when it hit the issue again, ran plaidml-setup just to be sure (doubt this matters), then ran mnist_cnn.py again. Loss was nan immediately.

> Andys-iMac-2:examples andy$ python mnist_cnn.py 
> x_train shape: (60000, 28, 28, 1)
> 60000 train samples
> 10000 test samples
> INFO:plaidml:Opening device "amd_radeon_pro_580_compute_engine.0
> Train on 60000 samples, validate on 10000 samples
> Epoch 1/12
> INFO:plaidml:Analyzing Ops: 85 of 285 operations complete
> 59904/60000 [============================>.] - ETA: 0s - loss: 0.3350 - acc: 0.8988INFO:plaidml:Analyzing Ops: 85 of 285 operations complete
> 60000/60000 [==============================] - 27s - loss: 0.3348 - acc: 0.8988 - val_loss: 0.0808 - val_acc: 0.9741
> Epoch 2/12
> 60000/60000 [==============================] - 18s - loss: 0.1197 - acc: 0.9648 - val_loss: 0.0695 - val_acc: 0.9787
> Epoch 3/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.3754 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 4/12
> 60000/60000 [==============================] - 18s - loss: nan - acc: 0.0000e+00 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 5/12
> 18176/60000 [========>.....................] - ETA: 12s - loss: nan - acc: 0.0000e+00^CTraceback (most recent call last):
>   File "mnist_cnn.py", line 69, in <module>
>     validation_data=(x_test, y_test))
>   File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 867, in fit
>     initial_epoch=initial_epoch)
>   File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 1598, in fit
>     validation_steps=validation_steps)
>   File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 1183, in _fit_loop
>     outs = f(ins_batch)
>   File "/usr/local/lib/python2.7/site-packages/plaidml/keras/backend.py", line 923, in __call__
>     self._invoker.invoke()
>   File "/usr/local/lib/python2.7/site-packages/plaidml/__init__.py", line 1316, in invoke
>     return Invocation(self._ctx, self)
>   File "/usr/local/lib/python2.7/site-packages/plaidml/__init__.py", line 1322, in __init__
>     self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
>   File "/usr/local/lib/python2.7/site-packages/plaidml/__init__.py", line 659, in _check_err
>     def _check_err(self, result, func, args):
> KeyboardInterrupt
> Andys-iMac-2:examples andy$ plaidml-setup
> 
> PlaidML Setup (0.1.1)
> 
> Thanks for using PlaidML!
> 
> Some Notes:
>   * Bugs and other issues: https://github.com/plaidml/plaidml
>   * Questions: https://stackoverflow.com/questions/tagged/plaidml
>   * Say hello: https://groups.google.com/forum/#!forum/plaidml-dev
>   * PlaidML is licensed under the GNU AGPLv3
>  
> Default Config Devices:
>    No devices.
> 
> Experimental Config Devices:
>    amd_radeon_pro_580_compute_engine.0 : AMD AMD Radeon Pro 580 Compute Engine
>    intel(r)_core(tm)_i5-7600k_cpu_@_3.80ghz.0 : Intel Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
> 
> Using experimental devices can cause poor performance, crashes, and other nastiness.
> 
> Enable experimental device support? (y,n)[n]:y
> 
> Multiple devices detected (You can override by setting PLAIDML_DEVICE_IDS).
> Please choose a default device:
> 
>    1 : amd_radeon_pro_580_compute_engine.0
>    2 : intel(r)_core(tm)_i5-7600k_cpu_@_3.80ghz.0
> 
> Default device? (1,2)[1]:1
> 
> Selected device:
>     amd_radeon_pro_580_compute_engine.0
> 
> PlaidML sends anonymous usage statistics to help guide improvements.
> We'd love your help making it better.
> 
> Enable telemetry reporting? (y,n)[y]:y
> 
> Almost done. Multiplying some matrices...
> Tile code:
>   function (B[X,Z], C[Z,Y]) -> (A) { A[x,y : X,Y] = +(B[x,z] * C[z,y]); }
> Whew. That worked.
> 
> Save settings to /Users/andy/.plaidml? (y,n)[y]:y
> Success!
> 
> Andys-iMac-2:examples andy$ python mnist_cnn.py 
> x_train shape: (60000, 28, 28, 1)
> 60000 train samples
> 10000 test samples
> INFO:plaidml:Opening device "amd_radeon_pro_580_compute_engine.0
> Train on 60000 samples, validate on 10000 samples
> Epoch 1/12
> 59776/60000 [============================>.] - ETA: 0s - loss: nan - acc: 0.8524INFO:plaidml:Analyzing Ops: 85 of 285 operations complete
> 60000/60000 [==============================] - 21s - loss: nan - acc: 0.8492 - val_loss: nan - val_acc: 0.0000e+00
> Epoch 2/12
> 49280/60000 [=======================>......] - ETA: 3s - loss: nan - acc: 0.0000e+00^CTraceback (most recent call last):
>   File "mnist_cnn.py", line 69, in <module>
>     validation_data=(x_test, y_test))
>   File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 867, in fit
>     initial_epoch=initial_epoch)
>   File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 1598, in fit
>     validation_steps=validation_steps)
>   File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 1183, in _fit_loop
>     outs = f(ins_batch)
>   File "/usr/local/lib/python2.7/site-packages/plaidml/keras/backend.py", line 925, in __call__
>     return [t.as_ndarray(_ctx) for t in tensors]
>   File "/usr/local/lib/python2.7/site-packages/plaidml/__init__.py", line 1133, in as_ndarray
>     ctypes.cast(None, _MAP_BUFFER_FUNCTYPE), None)
>   File "/usr/local/lib/python2.7/site-packages/plaidml/__init__.py", line 659, in _check_err
>     def _check_err(self, result, func, args):
> KeyboardInterrupt

**Comment by jbruestle** [comment] 2017-10-30 18:54
Can either of you try to the pip in #47?  I think this is the same issue.  It's looking like it might be a driver problem, but hopefully it can be worked around, although that is still unclear.

**Comment by yokoe** [comment] 2017-10-31 15:43
I tried new pip.
It seems to be working fine! Great!

**Comment by andyoneal** [comment] 2017-11-02 04:43
Looks fixed to me too.

> Andys-iMac-2:SpaceX andy$ pip install /Users/andy/Downloads/plaidml-0.0.0.dev0-py2.py3-none-macosx_10_10_x86_64.whl 
> Processing /Users/andy/Downloads/plaidml-0.0.0.dev0-py2.py3-none-macosx_10_10_x86_64.whl
> Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from plaidml==0.0.0.dev0)
> Requirement already satisfied: numpy in /usr/local/lib/python2.7/site-packages (from plaidml==0.0.0.dev0)
> Requirement already satisfied: requests in /usr/local/lib/python2.7/site-packages (from plaidml==0.0.0.dev0)
> Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/site-packages (from requests->plaidml==0.0.0.dev0)
> Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/site-packages (from requests->plaidml==0.0.0.dev0)
> Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/site-packages (from requests->plaidml==0.0.0.dev0)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/site-packages (from requests->plaidml==0.0.0.dev0)
> Installing collected packages: plaidml
> Successfully installed plaidml-0.0.0.dev0
> Andys-iMac-2:SpaceX andy$ cd ~/git/keras/examples
> Andys-iMac-2:examples andy$ python mnist_cnn.py 
> x_train shape: (60000, 28, 28, 1)
> 60000 train samples
> 10000 test samples
> INFO:plaidml:Opening device "amd_radeon_pro_580_compute_engine.0
> Train on 60000 samples, validate on 10000 samples
> Epoch 1/12
> 60000/60000 [==============================] - 28s - loss: 0.3312 - acc: 0.8994 - val_loss: 0.0840 - val_acc: 0.9731
> Epoch 2/12
> 60000/60000 [==============================] - 23s - loss: 0.1167 - acc: 0.9658 - val_loss: 0.0522 - val_acc: 0.9831
> Epoch 3/12
> 60000/60000 [==============================] - 23s - loss: 0.0855 - acc: 0.9743 - val_loss: 0.0447 - val_acc: 0.9853
> Epoch 4/12
> 60000/60000 [==============================] - 23s - loss: 0.0727 - acc: 0.9783 - val_loss: 0.0380 - val_acc: 0.9878
> Epoch 5/12
> 60000/60000 [==============================] - 24s - loss: 0.0621 - acc: 0.9808 - val_loss: 0.0347 - val_acc: 0.9877
> Epoch 6/12
> 60000/60000 [==============================] - 23s - loss: 0.0558 - acc: 0.9834 - val_loss: 0.0334 - val_acc: 0.9887
> Epoch 7/12
> 60000/60000 [==============================] - 23s - loss: 0.0513 - acc: 0.9849 - val_loss: 0.0351 - val_acc: 0.9880
> Epoch 8/12
> 60000/60000 [==============================] - 23s - loss: 0.0461 - acc: 0.9863 - val_loss: 0.0302 - val_acc: 0.9895
> Epoch 9/12
> 60000/60000 [==============================] - 23s - loss: 0.0441 - acc: 0.9866 - val_loss: 0.0301 - val_acc: 0.9898
> Epoch 10/12
> 60000/60000 [==============================] - 23s - loss: 0.0414 - acc: 0.9876 - val_loss: 0.0296 - val_acc: 0.9900
> Epoch 11/12
> 60000/60000 [==============================] - 23s - loss: 0.0401 - acc: 0.9879 - val_loss: 0.0295 - val_acc: 0.9901
> Epoch 12/12
> 60000/60000 [==============================] - 23s - loss: 0.0376 - acc: 0.9885 - val_loss: 0.0283 - val_acc: 0.9906
> Test loss: 0.0283074332476
> Test accuracy: 0.9906

**Comment by andyoneal** [comment] 2017-11-02 04:44
23s vs 18s though. Obviously the 23s runs actually resulted in good data, but wanted to point it out.

**Comment by jbruestle** [comment] 2017-11-02 23:17
Yes.  This is basically a work around that does somewhat impact performance, although only on the Mac.  We will eventually release a Metal backend for the Mac, at which point hopefully the driver issues will go away and we can use the original settings.

**Comment by jbruestle** [comment] 2017-11-02 23:19
Just pushed the fixes for this issue to master and uploaded the official pips!  Check out version 0.1.2...  Closing the ticket as fixed, please reopen if the new pips don't work for some reason.

**Comment by andyoneal** [comment] 2017-11-02 23:20
Tried mnist again after building with commit #55 and still hitting the nan issue. Will try with the pip.

**Comment by jbruestle** [comment] 2017-11-02 23:31
That's very odd, so you're saying your locally built version based of of the GitHub master is causing nan?  Technically the officially released pips for the Mac are still build using our internal repo (we are in the processed of moving out build automation + ci over to use the public repo still), but it should be in sync with the open source one, and moreover that specific bug fix change does appear to be in master on GitHub.

**Comment by andyoneal** [comment] 2017-11-02 23:35
Works fine with the pip version, even running at 19s per epoch now. I would assume I did something wrong while building. Will try again

**Comment by andyoneal** [comment] 2017-11-02 23:50
Yep. User error. Didn't fully clean up after the last build. All good.

**Comment by jbruestle** [comment] 2017-11-03 00:35
Good to hear.  Thanks for all you help finding this correctness problem and testing fixes!

**Comment by aldanor** [comment] 2018-03-02 12:34
Should the readme be updated? (still refers to this issue)

**Comment by jbruestle** [comment] 2018-03-03 00:15
Good catch!  Yes, looks like we need to fix the readme.

**Closed** 2018-03-06 03:20 UTC
