### ISSUE TITLE
CI support for Gen9 validation

### ISSUE THREAD

**Issue by jbruestle** [plaidml/plaidml#1246] opened 2020-08-04 23:18 UTC
Some method to allow CI to correctly test MLIR Gen9 lowering on actual hardware.

**Comment by jbruestle** [comment] 2020-08-04 23:19
Putting this in as sort of a placeholder since I'm haven't worked out the details.  Assigning @flaub to track/expand upon, please reassign if possible.

**Comment by flaub** [comment] 2020-09-21 21:53
I think this will be resolved when https://github.com/plaidml/plaidml/pull/1371 lands.

**Comment by adstraw** [comment] 2020-09-30 17:25
I filed a separate issue to get ResNet50 into CI for Intel Gen 9.  Owner is @drgone.  With that, is there anything else that needs to be done or can we close this issue?

Put ResNet50 into CI for Intel Gen9 gating V1 commits for correctness and performance:
https://github.com/plaidml/plaidml/issues/1401

**Comment by flaub** [comment] 2020-09-30 20:58
This is now a duplicate of #1401

**Closed by flaub** 2020-09-30 20:58 UTC
Labels: plaidmlv1
