### ISSUE TITLE
TypeError: unsupported operand type(s) for ** or pow(): 'Value' and 'float'

### ISSUE THREAD

**Issue by cassidys** [plaidml/plaidml#208] opened 2018-12-08 00:00 UTC
I'm working on a convolutional clustering algorithm based on this repository.

https://github.com/XifengGuo/DCEC/blob/master/DCEC.py

The issue occurs in the line which raises q to a power, q **= (self.alpha + 1.0) / 2.0

```
def call(self, inputs, **kwargs):
        """ student t-distribution, as same as used in t-SNE algorithm.
                 q_ij = 1/(1+dist(x_i, u_j)^2), then normalize it.
        Arguments:
            inputs: the variable containing data, shape=(n_samples, n_features)
        Return:
            q: student's t-distribution, or soft labels for each sample. shape=(n_samples, n_clusters)
        """
        q = 1.0 / (1.0 + (K.sum(K.square(K.expand_dims(inputs, axis=1) - self.clusters), axis=2) / self.alpha))
        q **= (self.alpha + 1.0) / 2.0
        q = K.transpose(K.transpose(q) / K.sum(q, axis=1))
        return q
```

I get the error 

  File "/AI Clustering/DCEC - custom.py", line 193, in call
    q = q ** (self.alpha + 1.0) / 2.0

TypeError: unsupported operand type(s) for ** or pow(): 'Value' and 'float'

I tried casting q which is a value to another type but it failed as well. The type for q is 
<class 'plaidml.tile.Value'>

**Comment by karamheen** [comment] 2019-01-17 00:00
https://github.com/XifengGuo/DEC-keras.git

$ python DEC.py --dataset mnist
Using plaidml.keras.backend backend.
Namespace(ae_weights=None, batch_size=256, dataset='mnist', maxiter=20000.0, pretrain_epochs=None, save_dir='results', tol=0.001, update_interval=None)
('MNIST samples', (70000, 784))
INFO:plaidml:Opening device "metal_amd_radeon_hd_-_firepro_d500.1"
/Users/test/plaidml-venv/lib/python2.7/site-packages/numpy/ctypeslib.py:389: 
  return array(obj, copy=False)
Traceback (most recent call last):
  File "DEC.py", line 321, in <module>
    dec = DEC(dims=[x.shape[-1], 500, 500, 2000, 10], n_clusters=n_clusters, init=init)
  File "DEC.py", line 138, in __init__
    clustering_layer = ClusteringLayer(self.n_clusters, name='clustering')(self.encoder.output)
  File "/Users/test/plaidml-venv/lib/python2.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "DEC.py", line 106, in call
    q **= (self.alpha + 1.0) / 2.0
TypeError: unsupported operand type(s) for ** or pow(): 'Value' and 'float'

Trying to run the code as is from this repo with plaidml as backend.

**Comment by brianretford** [comment] 2019-06-07 17:28
This should work in the latest version if you're interested in trying again. Sorry for the delay

**Comment by dgkutnic** [comment] 2019-06-14 17:14
Issues in the `needs info` state for 7+ days will be marked as obsolete and closed. If the issue is still occurring for you, please re-open the issue and provide us with the requested info.

**Closed by dgkutnic** 2019-06-14 17:14 UTC
Labels: needs info, obsolete

**Comment by mischki** [comment] 2021-01-22 20:07
I am experiencing the exact same problem with a DEC code. Has anyone been able to resolve this?
