### ISSUE TITLE
Duplicate binding when loading model and recompiling with new metrics

### ISSUE THREAD

**Issue by godfrey-cw** [plaidml/plaidml#211] opened 2018-12-10 11:25 UTC
Sorry the example is so involved, time permitting I'll try to cook up a minimal example of this behavior. 
I don't get any errors when I skip the recompile step (and use the old metrics, that the model was originally compiled with).

The model:

`class single_inst_lstm:
    def __init__(self, instrument='Piano',
                 time_steps=48, time_x=1,
                 time_y=1, 
                 hidden_units=[1000]):
        """instantiates a single-instrument LSTM 
        with the given parameters"""
        self.instrument = instrument
        self.time_steps = time_steps
        self.time_x = time_x
        self.time_y = time_y
        self.hidden_units = hidden_units
        # Set the input expectations
        x_in = Input(shape=(time_steps,
                            time_x*128))
        # The following allows for use with
        # 1 or multiple LSTM layers
        try:
            n_layers = len(hidden_units)
            if n_layers == 1:
                h = LSTM(hidden_units[0],
                         return_sequences=True)(x_in)
                last_hidden = hidden_units[0]
            else:
                h = LSTM(hidden_units[0],
                         return_sequences=True)(x_in)
                for i in range(1, n_layers):
                    h = LSTM(hidden_units[i],
                             return_sequences=True)(h)
                last_hidden = hidden_units[-1]
        except:
            print('hidden_units nust have ndim=0 or 1')
            raise
        
        # Ends with a dense layer
        # to achieve the desired output dim    
        y_out = Dense(time_y*128, activation='sigmoid',
                      input_shape=(last_hidden,))(h)
        self.model = Model(x_in, y_out)
        # Choose the optimizer/loss function
        rmsprop_opt = optimizers.RMSprop()
        loss_fun = losses.binary_crossentropy
        from metrics import polyphonic_rate, tonal_distance
        from metric import f_measure
        f_meas = f_measure(threshold=0.5).metric
        poly_rate = polyphonic_rate(threshold=0.5).metric
        t_dist = tonal_distance().metric
        self.model.compile(loss=loss_fun, optimizer=rmsprop_opt,
                           metrics=[metrics.mae,
                                    metrics.binary_accuracy,
                                    f_meas,
                                    poly_rate, t_dist])
`
The metric:
`
class tonal_distance:
    """Return the tonal distance [1] 
    between the two input pianorolls.

    [1] Christopher Harte, Mark Sandler, 
    and Martin Gasser. Detecting
    harmonic change in musical audio. 
    In Proc. ACM Workshop on Audio and
    Music Computing Multimedia, 2006.
    """
    def __init__(self, r1=1.0,
                 r2=1.0, r3=0.5):
        self.r1 = r1
        self.r2 = r2
        self.r3 = r3
 
        def tonal_matrix(r1, r2, r3):
            """Return a tonal matrix for computing the tonal
            distance."""
            tonal_matrix = np.empty((6, 12))
            tonal_matrix[0] = r1 * np.sin(np.arange(12)
                                          * (7. / 6.)
                                          * np.pi)
            tonal_matrix[1] = r1 * np.cos(np.arange(12)
                                          * (7. / 6.)
                                          * np.pi)
            tonal_matrix[2] = r2 * np.sin(np.arange(12)
                                          * (3. / 2.)
                                          * np.pi)
            tonal_matrix[3] = r2 * np.cos(np.arange(12)
                                          * (3. / 2.)
                                          * np.pi)
            tonal_matrix[4] = r3 * np.sin(np.arange(12)
                                          * (2. / 3.)
                                          * np.pi)
            tonal_matrix[5] = r3 * np.cos(np.arange(12)
                                          * (2. / 3.)
                                          * np.pi)
            return tonal_matrix

        self.tonal_matrix = bk.constant(tonal_matrix(self.r1,
                                                     self.r2, self.r3))
        # The indices finally work. Do not touch.
    def to_chroma(self, y):
        """Return the unnormalized chroma 
        features of a pianoroll."""
        reshaped1 = bk.reshape(y, (y.shape[1][0], 1, y.shape[1][1], y.shape[1][2]))
        padded = bk.spatial_2d_padding(reshaped1, ((0,0), (0,4)), data_format='channels_first')
        reshaped2 = bk.reshape(padded, (padded.shape[1][0],
                                        padded.shape[1][2], padded.shape[1][3]))
        reshaped3 = bk.reshape(reshaped2, (reshaped2.shape[1][0],
                                           reshaped2.shape[1][1], 11, 12))
        summed = bk.sum(reshaped3, axis=2)
        return summed

    def to_tonal_space(self, y):
            """Return the tensor in tonal 
            space """
            chroma = self.to_chroma(y)
            t_mat = self.tonal_matrix
            return bk.dot(chroma,
                          bk.transpose(t_mat))

    def metric(self, y_true, y_pred):
        """The actual tonal distance function"""
        mapped_true = self.to_tonal_space(y_true)
        mapped_pred = self.to_tonal_space(y_pred)
        N = mapped_true.shape[1][0]*mapped_true.shape[1][1]
        return bk.sqrt(bk.sum(bk.square(mapped_true-mapped_pred)))/N
`
And finally, reloading and trying to evaluate the new metrics:

`def test_network(network,
                 test_seq,
                 new_metrics,
                 dirname):
    """test a network on test_seq
    save results in directory dirname"""
    if new_metrics != None:
        # Recompile the network to include metrics
        loss = network.loss_functions[0]
        opt = network.optimizer
        network.compile(loss=loss,
                        optimizer=opt,
                        metrics=new_metrics)

    test_history = network.evaluate_generator(generator=test_seq,
                                              use_multiprocessing=True,
                                              workers=3,
                                              verbose=1)

    try:
        os.mkdir(dirname)
    except OSError as e:
        if e.errno != errno.EEXIST:
            raise
        
    with open(dirname+'/test_history.pickle', 'wb') as f:
        pk.dump(test_history, f)
`
The error:
`>>> INFO:plaidml:Opening device "opencl_intel_intel(r)_gen9_hd_graphics_neo.0"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/charles/Documents/DataScience/MachineLearning/Larghissimo/larghissimo/code/scripts/compute_new_metrics.py", line 70, in <module>
    dirname=results_dir+'/e_1_train_new_met')
  File "/home/charles/Documents/DataScience/MachineLearning/Larghissimo/larghissimo/code/scripts/train_val_test.py", line 120, in test_network
    verbose=1)
  File "/home/charles/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/charles/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/engine/training.py", line 1469, in evaluate_generator
    verbose=verbose)
  File "/home/charles/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/engine/training_generator.py", line 343, in evaluate_generator
    outs = model.test_on_batch(x, y, sample_weight=sample_weight)
  File "/home/charles/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/engine/training.py", line 1254, in test_on_batch
    outputs = self.test_function(ins)
  File "/home/charles/anaconda3/envs/larghissimo/lib/python3.6/site-packages/plaidml/keras/backend.py", line 165, in __call__
    self._invoker.invoke()
  File "/home/charles/anaconda3/envs/larghissimo/lib/python3.6/site-packages/plaidml/__init__.py", line 1432, in invoke
    return Invocation(self._ctx, self)
  File "/home/charles/anaconda3/envs/larghissimo/lib/python3.6/site-packages/plaidml/__init__.py", line 1438, in __init__
    self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
  File "/home/charles/anaconda3/envs/larghissimo/lib/python3.6/site-packages/plaidml/__init__.py", line 716, in _check_err
    self.raise_last_status()
  File "/home/charles/anaconda3/envs/larghissimo/lib/python3.6/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Duplicate binding discovered: X_I_7
>>> `

**Comment by brianretford** [comment] 2019-06-14 17:25
Thanks for the detailed report and apologies for the delayed response. If you're still interested can you try and reproduce this? We've made fixes in related areas, but we're not sure if this one has been fixed.

**Comment by dgkutnic** [comment] 2019-06-21 20:51
Issues in the `needs info` state for 7+ days will be marked as obsolete and closed. If the issue is still occurring for you, please re-open the issue and provide us with the requested info.

**Closed by dgkutnic** 2019-06-21 20:51 UTC
Labels: bug, needs info, obsolete
