### ISSUE TITLE
Multiprocessing with fit/predict/evaluate_generator doesn't time out

### ISSUE THREAD

**Issue by godfrey-cw** [plaidml/plaidml#212] opened 2018-12-10 16:13 UTC
I've run into this repeatedly this week. It's not always an issue, but for instance evaluate generator doesn't leave behind a model.history, so output from that isn't recoverable in any obvious way.
Here's the most recent traceback (keyboard interrupt 10 min after the CPU stopped spinning).:
`INFO:plaidml:Opening device "opencl_intel_intel(r)_gen9_hd_graphics_neo.0"
2510/2510 [==============================] - 570s 227ms/step
  C-c C-cTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/charles/Documents/DataScience/MachineLearning/Larghissimo/larghissimo/code/scripts/compute_new_metrics.py", line 74, in <module>
    dirname=results_dir+'/e_1_train_new_met')
  File "/home/charles/Documents/DataScience/MachineLearning/Larghissimo/larghissimo/code/scripts/train_val_test.py", line 120, in test_network
    verbose=1)
  File "/home/charles/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/charles/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/engine/training.py", line 1469, in evaluate_generator
    verbose=verbose)
  File "/home/charles/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/engine/training_generator.py", line 368, in evaluate_generator
    enqueuer.stop()
  File "/home/charles/anaconda3/envs/larghissimo/lib/python3.6/site-packages/keras/utils/data_utils.py", line 604, in stop
    self.run_thread.join(timeout)
  File "/home/charles/anaconda3/envs/larghissimo/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/home/charles/anaconda3/envs/larghissimo/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt`

**Comment by brianretford** [comment] 2019-06-07 17:21
Interesting. You could try the latest release with USE_STRIPE=1

**Comment by dgkutnic** [comment] 2019-06-14 17:13
Issues in the `needs info` state for 7+ days will be marked as obsolete and closed. If the issue is still occurring for you, please re-open the issue and provide us with the requested info.

**Closed by dgkutnic** 2019-06-14 17:13 UTC
Labels: needs info, obsolete
