### ISSUE TITLE
No support for Vega V8

### ISSUE THREAD

**Issue by hr21** [plaidml/plaidml#372] opened 2019-07-19 04:37 UTC
I use an amd Gpu with VegaV8 unfortunately plaidml dosen't support my system. NOt even 5% of Gpu is being used.

**Comment by brianretford** [comment] 2019-07-19 17:07
We need the output of `clinfo` and `plaidml-setup`

**Comment by dgkutnic** [comment] 2019-07-26 17:41
Issues in the `needs info` state for 7+ days will be marked as obsolete and closed. If the issue is still occurring for you, please re-open the issue and provide us with the requested info.

**Closed by dgkutnic** 2019-07-26 17:41 UTC
Labels: needs info, obsolete
