### ISSUE TITLE
NotImplementedError: rnn is not implemented with mask support

### ISSUE THREAD

**Issue by nietao2** [plaidml/plaidml#325] opened 2019-05-31 07:24 UTC
When using the LSTM with mask-enabled Embedding, i get an exception which shows "NotImplementedError: rnn is not implemented with mask support"

Here is part of my code
```python
language_input = Input(shape=(max_length,))
language_model = Embedding(vocab_size, 50, input_length=max_length, mask_zero=True)(language_input)
language_model = LSTM(128, return_sequences=True)(language_model)
language_model = LSTM(128, return_sequences=True)(language_model)
decoder = concatenate([encoded_image, language_model])
decoder = LSTM(512, return_sequences=True)(decoder)
decoder = LSTM(512, return_sequences=False)(decoder)
decoder = Dense(vocab_size, activation='softmax')(decoder)
```
Here is the error showed when i run the code.
```exception
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "metal_amd_radeon_pro_560.0"
Traceback (most recent call last):
  File "/Users/nietao/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-64e3a343a34d>", line 1, in <module>
    runfile('/Users/nietao/IdeaProjects/Screenshot-to-code-in-Keras/Bootstrap/bootstrap.py', wdir='/Users/nietao/IdeaProjects/Screenshot-to-code-in-Keras/Bootstrap')
  File "/Users/nietao/Library/Application Support/IntelliJIdea2018.2/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Users/nietao/Library/Application Support/IntelliJIdea2018.2/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/nietao/IdeaProjects/Screenshot-to-code-in-Keras/Bootstrap/bootstrap.py", line 135, in <module>
    language_model = LSTM(128, return_sequences=True)(language_model)
  File "/Users/nietao/anaconda3/lib/python3.7/site-packages/keras/layers/recurrent.py", line 532, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/Users/nietao/anaconda3/lib/python3.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/nietao/anaconda3/lib/python3.7/site-packages/keras/layers/recurrent.py", line 2194, in call
    initial_state=initial_state)
  File "/Users/nietao/anaconda3/lib/python3.7/site-packages/keras/layers/recurrent.py", line 649, in call
    input_length=timesteps)
  File "/Users/nietao/anaconda3/lib/python3.7/site-packages/plaidml/keras/backend.py", line 1315, in rnn
    raise NotImplementedError('rnn is not implemented with mask support')
NotImplementedError: rnn is not implemented with mask support
```
I notice that the rnn with mask haven't been implemented in the `backend.py` yet. Do you have any plan to add this support later?

**Comment by dgkutnic** [comment] 2019-05-31 17:26
This is a duplicate of #215 - we'd love any help we can get with supporting RNNs in PlaidML!

**Closed by dgkutnic** 2019-05-31 17:26 UTC
Labels: help wanted, rnn
