### ISSUE TITLE
"Analyzing Ops", followed by "Unable to Compile Tile Program"

### ISSUE THREAD

**Issue by crowoy** [plaidml/plaidml#207] opened 2018-12-05 12:39 UTC
I am attempting to train multiple models using the inbuilt AMD GPU in my MacBook Pro. The models train without issue with Keras/Tensorflow (CPU). When I enable Keras/PlaidML (OpenCL-CPU, OpenCL-GPU, or Metal-GPU) then I get the output below:

```
========== Total Models: 1 ==========
========== Configuration (1/1) ==========
---------- Creating Folders... ----------
Info string: 2018-12-05_12-23-25
Run directory: outputs/2018-12-05_12-23-25/ep01000_bs00032_ws00200_nn00200_lr0-001/
Data : ../data/
---------- Model (in configuration) 1/1----------
---------- Building and Training Model ----------
INFO:plaidml:Opening device "opencl_amd_amd_radeon_pro_560x_compute_engine.0"
Compilation Time (s) : 0.00251913070679
Train on 2227 samples, validate on 394 samples
Epoch 1/1000
INFO:plaidml:Analyzing Ops: 2672 of 38574 operations complete
INFO:plaidml:Analyzing Ops: 6614 of 38574 operations complete
INFO:plaidml:Analyzing Ops: 10041 of 38574 operations complete
INFO:plaidml:Analyzing Ops: 13385 of 38574 operations complete
INFO:plaidml:Analyzing Ops: 18440 of 38574 operations complete
INFO:plaidml:Analyzing Ops: 24353 of 38574 operations complete
INFO:plaidml:Analyzing Ops: 31246 of 38574 operations complete
INFO:plaidml:Analyzing Ops: 35172 of 38574 operations complete
```

After it hits this line, it hangs for a few minutes, then outputs over 100,000 lines of C/C++ code, followed by:

```
WARNING:plaidml:Failed to build program: CL_BUILD_PROGRAM_FAILURE
[Traceback]
plaidml.exceptions.Unknown: Unable to compile Tile program
```

**Comment by brianretford** [comment] 2018-12-05 19:45
What version of macOS are you using? And can you zip up the entire output and send it to brian.retford@intel.com?

**Comment by crowoy** [comment] 2018-12-06 00:31
Currently using macOS 10.14.1. I've sent the full output to your email address.

**Comment by diegojrendonb** [comment] 2018-12-12 03:20
I have the same problem with a iMac (Mid 2017-MacOS 10.14.1) with a GPU Radeon Pro 560. I also notice in the monitor activity that the process CVMCompiler was using 100% CPU the minutes before Error occurred.

 I used PlaidML opencl_amd_amd_radeon_pro_560_compute_engine.0 as selected device.

The error was the following

> WARNING:plaidml:Failed to build program: CL_BUILD_PROGRAM_FAILURE
> Traceback (most recent call last):
> 
>   File "<ipython-input-10-ac797fa6c03f>", line 1, in <module>
>     Model1.fit(X_train,y_train,epochs=6,batch_size=256)
> 
>   File "/Users/**/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1037, in fit
>     validation_steps=validation_steps)
> 
>   File "/Users/**/anaconda3/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop
>     outs = f(ins_batch)
> 
>   File "/Users/**/anaconda3/lib/python3.6/site-packages/plaidml/keras/backend.py", line 165, in __call__
>     self._invoker.invoke()
> 
>   File "/Users/**/anaconda3/lib/python3.6/site-packages/plaidml/__init__.py", line 1432, in invoke
>     return Invocation(self._ctx, self)
> 
>   File "/Users/**/anaconda3/lib/python3.6/site-packages/plaidml/__init__.py", line 1438, in __init__
>     self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
> 
>   File "/Users/**/anaconda3/lib/python3.6/site-packages/plaidml/__init__.py", line 716, in _check_err
>     self.raise_last_status()
> 
>   File "/Users/**/anaconda3/lib/python3.6/site-packages/plaidml/library.py", line 131, in raise_last_status
>     raise self.last_status()
> 
> Unknown: Unable to compile Tile program

Thanks for suggestions on how to fix issue.

**Comment by brianretford** [comment] 2018-12-12 05:34
Does it reproduce for you if you use metal instead? We made a lot of fixes for 0.5, which is checked in but hasn't been released in binary form yet. Hoping to get to that very soon.

**Comment by maechler** [comment] 2019-01-31 13:40
@brianretford I had the same issue using `opencl_amd_amd_radeon_pro_555x_compute_engine.0`, but managed to get the same script working by changing to `metal_amd_radeon_pro_560.0` using the `plaidml-setup` command.

**Comment by brianretford** [comment] 2019-06-07 17:31
duplicate of #112

**Closed by brianretford** 2019-06-07 17:31 UTC

**Comment by RxxxxR** [comment] 2020-05-19 08:54
My imac Radeon Pro 580X also encountered the same problem

**Comment by brcpaul** [comment] 2020-11-05 14:20
Same issue but changing to metal doesn't help...
