### ISSUE TITLE
Syntax error on prediction

### ISSUE THREAD

**Issue by nimaaghli** [plaidml/plaidml#311] opened 2019-05-16 18:58 UTC
Hi,
I have a piece of code that runs with tf back-end. When I change it to plaidml backend I get this error on `.predict(input) `

```
ERROR:plaidml:syntax error, unexpected -, expecting "," or ) : function (
  X_I_0[X_I_0_0, X_I_0_1, X_I_0_2, X_I_0_3],
  X_I_1[X_I_1_0, X_I_1_1],
  X_I_2[X_I_2_0, X_I_2_1],
  X_I_3[X_I_3_0, X_I_3_1, X_I_3_2, X_I_3_3],
  X_I_4[X_I_4_0, X_I_4_1],
  X_I_5[X_I_5_0, X_I_5_1, X_I_5_2, X_I_5_3],
  X_I_6[X_I_6_0, X_I_6_1, X_I_6_2, X_I_6_3],
  X_I_7[X_I_7_0, X_I_7_1, X_I_7_2, X_I_7_3],
  X_I_8[X_I_8_0],
  X_I_9[X_I_9_0, X_I_9_1, X_I_9_2],
  X_I_10[X_I_10_0],
  X_I_11[X_I_11_0, X_I_11_1, X_I_11_2],
  X_I_12[X_I_12_0],
  X_I_13[X_I_13_0, X_I_13_1, X_I_13_2],
  X_I_14[X_I_14_0],
  X_I_15[X_I_15_0, X_I_15_1, X_I_15_2, X_I_15_3],
  X_I_16[X_I_16_0]
) -> (
  X_T71,
  X_T74
) {
  [[pid(conv3)]] X_T4[i, j, ci, co : 6, 3, 16, 32] = +(X_I_2[i, k] * X_I_3[k, j, ci, co]);
  [[pid(conv3)]] X_T5[i, j, ci, co : 6, 6, 16, 32] = +(X_T4[i, k, ci, co] * X_I_2[j, k]);
  [[pid(conv2)]] X_T7[i, j, ci, co : 6, 3, 10, 16] = +(X_I_2[i, k] * X_I_5[k, j, ci, co]);
  [[pid(conv2)]] X_T8[i, j, ci, co : 6, 6, 10, 16] = +(X_T7[i, k, ci, co] * X_I_2[j, k]);
  [[pid(conv1)]] X_T11[n, x0, x1, co : 1, 498, 886, 10] = +(X_I_6[n, k0 + x0, k1 + x1, ci] * X_I_7[k0, k1, ci, co]);
  [[pid(Reshape)]] X_T12 = reshape(X_I_8, X_I_6_0, X_I_6_0, X_I_6_0, X_I_8_0);
  [[pid(Add)]] X_T13 = add(X_T11, X_T12);
  X_T75 = 0.0;
  [[pid(relu_0)]] X_T76 = cmp_lt(X_T13, X_T75);
  X_T77 = 0.0;
  [[pid(relu_1)]] X_T14 = cond(X_T76, X_T77, X_T13);
  [[pid(Negate)]] X_T15 = neg(X_I_9);
  [[pid(Negate)]] X_T16 = neg(X_T13);
  X_T79 = 0.0;
  [[pid(relu_0)]] X_T80 = cmp_lt(X_T16, X_T79);
  X_T81 = 0.0;
  [[pid(relu_1)]] X_T17 = cond(X_T80, X_T81, X_T16);
  [[pid(Mul)]] X_T18 = mul(X_T15, X_T17);
  [[pid(Add)]] X_T19 = add(X_T14, X_T18);
  [[pid(max_pooling2d_1)]] X_T22[n, x0, x1, c : 1, 249, 443, 10] = >(X_T19[n, k0 + 2*x0, k1 + 2*x1, c]), k0 < 2, k1 < 2;
  [[pid(conv2)]] X_T27[n, i, j, x, y, ci : 1, 6, 6, 62, 111, 10] = +(X_I_4[k, i] * X_T22[n, k + 4*x, j + 4*y, ci]);
  [[pid(conv2)]] X_T28[n, i, j, x, y, ci : 1, 6, 6, 62, 111, 10] = +(X_T27[n, i, k, x, y, ci] * X_I_4[k, j]);
  [[pid(conv2)]] X_T29[n, i, j, x, y, co : 1, 6, 6, 62, 111, 16] = +(X_T28[n, i, j, x, y, ci] * X_T8[i, j, ci, co]);
  [[pid(conv2)]] X_T30[n, i, j, x, y, co : 1, 4, 6, 62, 111, 16] = +(X_I_1[k, i] * X_T29[n, k, j, x, y, co]);
  [[pid(conv2)]] X_T34[n, i + 4*x, j + 4*y, co : 1, 247, 441, 16] = +(X_T30[n, i, k, x, y, co] * X_I_1[k, j]) no_defract;
  [[pid(Reshape)]] X_T35 = reshape(X_I_10, X_I_9_1, X_I_9_1, X_I_9_1, X_I_10_0);
  [[pid(Add)]] X_T36 = add(X_T34, X_T35);
  X_T83 = 0.0;
  [[pid(relu_0)]] X_T84 = cmp_lt(X_T36, X_T83);
  X_T85 = 0.0;
  [[pid(relu_1)]] X_T37 = cond(X_T84, X_T85, X_T36);
  [[pid(Negate)]] X_T38 = neg(X_I_11);
  [[pid(Negate)]] X_T39 = neg(X_T36);
  X_T87 = 0.0;
  [[pid(relu_0)]] X_T88 = cmp_lt(X_T39, X_T87);
  X_T89 = 0.0;
  [[pid(relu_1)]] X_T40 = cond(X_T88, X_T89, X_T39);
  [[pid(Mul)]] X_T41 = mul(X_T38, X_T40);
  [[pid(Add)]] X_T42 = add(X_T37, X_T41);
  [[pid(conv3)]] X_T48[n, i, j, x, y, ci : 1, 6, 6, 62, 110, 16] = +(X_I_4[k, i] * X_T42[n, k + 4*x, j + 4*y, ci]);
  [[pid(conv3)]] X_T49[n, i, j, x, y, ci : 1, 6, 6, 62, 110, 16] = +(X_T48[n, i, k, x, y, ci] * X_I_4[k, j]);
  [[pid(conv3)]] X_T50[n, i, j, x, y, co : 1, 6, 6, 62, 110, 32] = +(X_T49[n, i, j, x, y, ci] * X_T5[i, j, ci, co]);
  [[pid(conv3)]] X_T51[n, i, j, x, y, co : 1, 4, 6, 62, 110, 32] = +(X_I_1[k, i] * X_T50[n, k, j, x, y, co]);
  [[pid(conv3)]] X_T55[n, i + 4*x, j + 4*y, co : 1, 245, 439, 32] = +(X_T51[n, i, k, x, y, co] * X_I_1[k, j]) no_defract;
  [[pid(Reshape)]] X_T56 = reshape(X_I_12, X_I_11_1, X_I_11_1, X_I_11_1, X_I_12_0);
  [[pid(Add)]] X_T57 = add(X_T55, X_T56);
  X_T91 = 0.0;
  [[pid(relu_0)]] X_T92 = cmp_lt(X_T57, X_T91);
  X_T93 = 0.0;
  [[pid(relu_1)]] X_T58 = cond(X_T92, X_T93, X_T57);
  [[pid(Negate)]] X_T59 = neg(X_I_13);
  [[pid(Negate)]] X_T60 = neg(X_T57);
  X_T95 = 0.0;
  [[pid(relu_0)]] X_T96 = cmp_lt(X_T60, X_T95);
  X_T97 = 0.0;
  [[pid(relu_1)]] X_T61 = cond(X_T96, X_T97, X_T60);
  [[pid(Mul)]] X_T62 = mul(X_T59, X_T61);
  [[pid(Add)]] X_T63 = add(X_T58, X_T62);
  [[pid(conv4-1)]] X_T64[n, x0, x1, co : 1, 245, 439, 2] = +(X_T63[n, k0 + x0, k1 + x1, ci] * X_I_0[k0, k1, ci, co]);
  [[pid(Reshape)]] X_T65 = reshape(X_I_14, X_I_13_1, X_I_13_1, X_I_13_1, X_I_14_0);
  [[pid(Add)]] X_T66 = add(X_T64, X_T65);
  [[pid(MaxReduce)]] X_T67[x0, x1, x2, sx3 : 1, 245, 439, 1] = >(X_T66[x0, x1, x2, x3]);
  [[pid(Sub)]] X_T68 = sub(X_T66, X_T67);
  [[pid(Exp)]] X_T69 = exp(X_T68);
  [[pid(Summation)]] X_T70[x0, x1, x2, sx3 : 1, 245, 439, 1] = +(X_T69[x0, x1, x2, x3]);
  [[pid(TrueDiv)]] X_T71 = div(X_T69, X_T70);
  [[pid(conv4-2)]] X_T72[n, x0, x1, co : 1, 245, 439, 4] = +(X_T63[n, k0 + x0, k1 + x1, ci] * X_I_15[k0, k1, ci, co]);
  [[pid(Reshape)]] X_T73 = reshape(X_I_16, X_I_15_1, X_I_15_1, X_I_15_1, X_I_16_0);
  [[pid(Add)]] X_T74 = add(X_T72, X_T73);
}
```

Here is how I load the network weights :
```

from keras.layers import Conv2D, Input,MaxPool2D, Reshape,Activation,Flatten, Dense, Permute
from keras.models import Model, Sequential
from keras.layers.advanced_activations import PReLU 
def create_Kao_Pnet( weight_path = 'model12old.h5'):
    input = Input(shape=[None, None, 3])
    x = Conv2D(10, (3, 3), strides=1, padding='valid', name='conv1')(input)
    x = PReLU(shared_axes=[1,2],name='PReLU1')(x)
    x = MaxPool2D(pool_size=2)(x)
    x = Conv2D(16, (3, 3), strides=1, padding='valid', name='conv2')(x)
    x = PReLU(shared_axes=[1,2],name='PReLU2')(x)
    x = Conv2D(32, (3, 3), strides=1, padding='valid', name='conv3')(x)
    x = PReLU(shared_axes=[1,2],name='PReLU3')(x)
    classifier = Conv2D(2, (1, 1), activation='softmax', name='conv4-1')(x)
    bbox_regress = Conv2D(4, (1, 1), name='conv4-2')(x)
    model = Model([input], [classifier, bbox_regress])
    model.load_weights(weight_path, by_name=True)
    return model
```

and here is how I prepare my data and feed it to the network for prediction:
```
Pnet = create_Kao_Pnet('12net.h5')
def detectFace(img, threshold):

    caffe_img = (img.copy() - 127.5) / 127.5
    origin_h, origin_w, ch = caffe_img.shape
    scales = tools.calculateScales(img)
    out = []
    t0 = time.time()
    # del scales[:4]

    for scale in scales:
        hs = int(origin_h * scale)
        ws = int(origin_w * scale)
        scale_img = cv2.resize(caffe_img, (ws, hs))
        input = scale_img.reshape(1, *scale_img.shape)
        print(input.shape)
        ouput = Pnet.predict(input) #error here 

```

The input shape is : (1, 500, 888, 3)

**Comment by dgkutnic** [comment] 2019-05-20 18:09
Hi Nima,

At the moment, PlaidML doesn't allow special characters (i.e. `-`) in variable names. I noticed the following two lines in your function `create_Kao_Pnet`:
```python3
    classifier = Conv2D(2, (1, 1), activation='softmax', name='conv4-1')(x)
    bbox_regress = Conv2D(4, (1, 1), name='conv4-2')(x)
```
Could you modify those lines as follows, then rerun with PlaidML?
```python3
    classifier = Conv2D(2, (1, 1), activation='softmax', name='conv4_1')(x)
    bbox_regress = Conv2D(4, (1, 1), name='conv4_2')(x)
```

Meanwhile, we will work on supporting variable names that contain special characters.

**Comment by dgkutnic** [comment] 2019-05-24 18:00
Duplicate of #241

**Closed by dgkutnic** 2019-05-24 18:00 UTC
Labels: bug
