### ISSUE TITLE
plaidml:b'syntax error, unexpected ), expecting }' b'Out of memory' (Keras 2.1.2 with mobilenet)

### ISSUE THREAD

**Issue by asurinha** [plaidml/plaidml#88] opened 2018-03-06 15:44 UTC
Hello!

I am trying to run plaidbench - plaidml in keras 2.1.2 but I got this error:

`INFO:plaidml:b'Opening device "ellesmere.0"'
ERROR:plaidml:b'syntax error, unexpected ), expecting ( : function (I[N0, N1]) -> (O) {\n  O = reshape(I, _Op(slice), 1, 1, 1024);\n}'
b'Out of memory'
Traceback:
_Op(reshape)
outputs: O
inputs:
  I: _Op(mean)
  outputs: O
  inputs:
    I: _Op(relu)
    outputs: R
    inputs:
      X: _Op(switch)
      outputs: O
      inputs:
        C: conv1_bn/placeholder_1[]
        conv1_bn/placeholder_1[]
        T: _Op(+)
        outputs: A
        inputs:
          ...truncated...
        E: _Op(+)
        outputs: A
        inputs:
          ...truncated...
      Alpha: 0.0
      0.0
      MaxValue: 6
      6
`

In keras 2.0.8 it's works. But I need to run an application that needs keras 2.1.2  together plaidml.

Thanks!

**Comment by brianretford** [comment] 2018-03-06 23:18
Could you share the application with us? Or a simple reproduction case?

**Comment by asurinha** [comment] 2018-03-07 17:41
The error occurs in 2  different occasions.

The first is when I try to run  `python3 plaidbench.py mobilenet` in the terminal using keras v.2.1.2. The error  is :  

`INFO:plaidml:b'Opening device "ellesmere.0"' ERROR:plaidml:b'syntax error, unexpected ), expecting ( : function (I[N0, N1]) -> (O) {\n O = reshape(I, _Op(slice), 1, 1, 1024);\n}' b'Out of memory' Traceback: _Op(reshape) outputs: O inputs: I: _Op(mean) outputs: O inputs: I: _Op(relu) outputs: R inputs: X: _Op(switch) outputs: O inputs: C: conv1_bn/placeholder_1[] conv1_bn/placeholder_1[] T: _Op(+) outputs: A inputs: ...truncated... E: _Op(+) outputs: A inputs: ...truncated... Alpha: 0.0 0.0 MaxValue: 6 6`

The second  occasion happens when I try to run keras-facenet  that needs keras v2.1.2 (https://github.com/nyoki-mtl/keras-facenet) 

Here my code:
`import plaidml.keras
plaidml.keras.install_backend()
from keras.models import load_model

model_path = 'model/keras/model/facenet_keras.h5'
model = load_model(model_path)`

and the exit is:

`  from ._conv import register_converters as _register_converters
INFO:plaidml:b'Opening device "ellesmere.0"'
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    model = load_model(model_path)
  File "/home/erehzio/Projects/keras-facenet/facenet_enviromnet/lib/python3.6/site-packages/keras/models.py", line 243, in load_model
    topology.load_weights_from_hdf5_group(f['model_weights'], model.layers)
  File "/home/erehzio/Projects/keras-facenet/facenet_enviromnet/lib/python3.6/site-packages/keras/engine/topology.py", line 3130, in load_weights_from_hdf5_group
    original_backend)
  File "/home/erehzio/Projects/keras-facenet/facenet_enviromnet/lib/python3.6/site-packages/keras/engine/topology.py", line 3022, in preprocess_weights_for_loading
    if _need_convert_kernel(original_backend):
  File "/home/erehzio/Projects/keras-facenet/facenet_enviromnet/lib/python3.6/site-packages/keras/engine/topology.py", line 3075, in _need_convert_kernel
    return uses_correlation[original_backend] != uses_correlation[K.backend()]
KeyError: 'plaidml'`


Thanks again!

**Comment by tzerrell** [comment] 2018-03-07 19:49
Quick update: we have a fix currently undergoing internal testing that addresses this. We have confirmed that it fixes the `python3 plaidbench.py mobilenet` bug; we are currently ensuring that it didn't break any other tests.

However, it does not fix the keras-facenet bug. That bug is due to Keras hardcoding a list of backend names in `keras/engine/topology.py:_need_convert_kernel`. We have a plan for a workaround, but are still working on implementing it.

Hopefully we will be able to update with both fixes soon!

**Comment by asurinha** [comment] 2018-03-08 11:24
thank you very much

**Comment by tzerrell** [comment] 2018-03-08 19:02
Leaving this open until we actually have the fix in

**Comment by tzerrell** [comment] 2018-03-27 17:22
The plaidml sytax error should be fixed in 0.3.0rc2, which you can install with `plaidml-keras==0.3.0rc2`. Let us know if it works!

Getting a good fix for the `_need_convert_kernel` error is somewhat involved and we haven't had a chance to get to it yet. If it's still a problem for you, please open a new issue for it to help us stay organized about it. We could also discuss potential workarounds in that issue.

**Closed** 2018-04-05 18:33 UTC
