### ISSUE TITLE
Support using system-installed llvm

### ISSUE THREAD

**Issue by KOLANICH** [plaidml/plaidml#1992] opened 2023-02-14 16:49 UTC
I mean the one from https://apt.llvm.org/unstable/

**Comment by hfp** [comment] 2023-02-14 19:13
Is this meant for the PlaidML v1-branch or the 0.7-release series?  I doubt any PlaidML can be mixed and matched using an LLVM of your choice. As far as PlaidML v1 goes, a specific SHA is needed, which renders this request somewhat pointless. Please let me know if I misunderstood your request or please add some more background.

**Comment by KOLANICH** [comment] 2023-02-14 19:46
v1 branch.

And you have understood right, I mean the setting to disable fetching LLVM and instead use the system-installed one. If it turns out the LLVM version is compatible, then good. If it turns out the PlaidML code is incompatible to the interface in the most recent LLVM version, it is a bug that has to be fixed, not concealed (we shouldn't be tied to obsolete versions of LLVM having no future, should we?)

**Comment by hfp** [comment] 2023-02-14 21:26
> If it turns oit the LLVM version is compatible

No, it does not work like this. Almost every project using MLIR from LLVM project relies on specific commits as both pieces ("the project") and MLIR are moving targets or are under development. Sorry, this business is not about updating to a newer version without adjusting the source code.

> If it turns out the PlaidML code is incompatibpe to the interface in the most recent LLVM version

It will be incompatible; see above.

> it is a bug that has to be fixed

No, it's not a bug but serious work is needed (continuously). Also, development of PlaidML stopped. In particular v1-branch never reached production. This is a research project which takes a refined road when compared to v1-branch (see also https://github.com/plaidml/plaidml/issues/1991#issuecomment-1428104437).

**Closed as completed** 2023-02-15 08:09 UTC

**Comment by KOLANICH** [comment] 2023-02-15 11:46
Thanks for the info.
