### ISSUE TITLE
plaidml.exceptions.Unknown: Duplicate updates

### ISSUE THREAD

**Issue by phobrain** [plaidml/plaidml#59] opened 2017-11-12 00:08 UTC
Setup:

    sudo apt-get install clinfo
    clinfo [sees 1080ti]
    sudo pip install -U plaidml-keras
    plaidml-setup
    [insert before keras import:]
    import plaidml.keras
    plaidml.keras.install_backend()

But, intermediate problem:

     ImportError: No module named plaidml.keras
    $ which python
    /home/phobrain/anaconda2/bin//python

Fix:

    sys.path.append('/usr/local/lib/python2.7/dist-packages/')
    import plaidml.keras
    plaidml.keras.install_backend()

'Real' issue being reported:

  File "siaconv.py", line 919, in doit
    epochs=epochs)
  File "/home/phobrain/anaconda2/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/phobrain/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1926, in fit_generator
    self._make_train_function()
  File "/home/phobrain/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 967, in _make_train_function
    **self._function_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/plaidml/keras/backend.py", line 1718, in function
    return _Function(inputs, outputs, updates, name)
  File "/usr/local/lib/python2.7/dist-packages/plaidml/keras/backend.py", line 931, in __init__
    c.add_update(_plaidml_val(var), _plaidml_val(newval))
  File "/usr/local/lib/python2.7/dist-packages/plaidml/__init__.py", line 1289, in add_update
    _lib().plaidml_add_composer_update(self, dest, src)
  File "/usr/local/lib/python2.7/dist-packages/plaidml/__init__.py", line 674, in _check_err
    self.raise_last_status()
  File "/usr/local/lib/python2.7/dist-packages/plaidml/library.py", line 136, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Duplicate updates

    model.fit_generator(
            myGen('data', tr_pairs, tr_y, batch_size, True),
            (len(tr_pairs)-1) / batch_size,
            validation_data=myGen('valid', te_pairs, te_y, batch_size, True),
            validation_steps=1,
            max_queue_size=2,
            workers=1,
            epochs=epochs)

Net:

    KERNEL_INIT = 'glorot_normal'

        seq.add(Dense(dense_size, input_shape=input_shape,
                    activation='relu', kernel_initializer=KERNEL_INIT))
        seq.add(BatchNormalization())
        seq.add(Dense((dense_size*2)/3,
                activation='relu',
                kernel_initializer=KERNEL_INIT))
        seq.add(Dropout(0.1, seed=SEED))
        seq.add(Dense(dense_size/4,
                activation='relu',
                kernel_initializer=KERNEL_INIT))
        seq.add(Dense((dense_size*2)/3,
                activation='relu',
                kernel_initializer=KERNEL_INIT))
        seq.add(Dense(dense_size,
                activation='relu',
                kernel_initializer=KERNEL_INIT))
        seq.add(Dense(512,
                    activation='relu',
                    kernel_initializer=KERNEL_INIT))
        seq.add(Dense(256,
                    activation='relu',
                    kernel_initializer=KERNEL_INIT))
        seq.add(Dense(128,
                    activation='relu',
                    kernel_initializer=KERNEL_INIT))
        seq.add(Dense(256,
                    activation='relu',
                    kernel_initializer=KERNEL_INIT))
        seq.add(Dense(128,
                    activation='relu',
                    kernel_initializer=KERNEL_INIT))

**Comment by jbruestle** [comment] 2017-11-12 22:10
Interesting.  I'm fairly sure the source of the error is in tile/lang/compose.cc, but it's unclear to me what would trigger such an error.  Generally, it's would caused by multiple updates to the same tensor in a single Tile function, but to my knowledge Keras doesn't typically issue such updates in non-recurrent networks (which we currently don't support, but are hoping to, see issue #24).    Your network doesn't appear to be doing anything that would tigger such an error.  Is it possible for you to send us a complete python file we could run to attempt a repro?

**Comment by phobrain** [comment] 2017-11-12 23:02
Have you tried any Siamese nets? Here's what I started from, for simplicity:

'''Train a Siamese MLP on pairs of digits from the MNIST dataset.
It follows Hadsell-et-al.'06 [1] by computing the Euclidean distance on the
output of the shared network and by optimizing the contrastive loss (see paper
for mode details).
[1] "Dimensionality Reduction by Learning an Invariant Mapping"
    http://yann.lecun.com/exdb/publis/pdf/hadsell-chopra-lecun-06.pdf
Gets to 99.5% test accuracy after 20 epochs.
3 seconds per epoch on a Titan X GPU
'''
from __future__ import absolute_import
from __future__ import print_function
import numpy as np

import random
from keras.datasets import mnist
from keras.models import Sequential, Model
from keras.layers import Dense, Dropout, Input, Lambda
from keras.optimizers import RMSprop
from keras import backend as K


def euclidean_distance(vects):
    x, y = vects
    return K.sqrt(K.maximum(K.sum(K.square(x - y), axis=1, keepdims=True), K.epsilon()))


def eucl_dist_output_shape(shapes):
    shape1, shape2 = shapes
    return (shape1[0], 1)


def contrastive_loss(y_true, y_pred):
    '''Contrastive loss from Hadsell-et-al.'06
    http://yann.lecun.com/exdb/publis/pdf/hadsell-chopra-lecun-06.pdf
    '''
    margin = 1
    return K.mean(y_true * K.square(y_pred) +
                  (1 - y_true) * K.square(K.maximum(margin - y_pred, 0)))


def create_pairs(x, digit_indices):
    '''Positive and negative pair creation.
    Alternates between positive and negative pairs.
    '''
    pairs = []
    labels = []
    n = min([len(digit_indices[d]) for d in range(10)]) - 1
    for d in range(10):
        for i in range(n):
            z1, z2 = digit_indices[d][i], digit_indices[d][i + 1]
            pairs += [[x[z1], x[z2]]]
            inc = random.randrange(1, 10)
            dn = (d + inc) % 10
            z1, z2 = digit_indices[d][i], digit_indices[dn][i]
            pairs += [[x[z1], x[z2]]]
            labels += [1, 0]
    return np.array(pairs), np.array(labels)


def create_base_network(input_dim):
    '''Base network to be shared (eq. to feature extraction).
    '''
    seq = Sequential()
    seq.add(Dense(128, input_shape=(input_dim,), activation='relu'))
    seq.add(Dropout(0.1))
    seq.add(Dense(128, activation='relu'))
    seq.add(Dropout(0.1))
    seq.add(Dense(128, activation='relu'))
    return seq


def compute_accuracy(predictions, labels):
    '''Compute classification accuracy with a fixed threshold on distances.
    '''
    return labels[predictions.ravel() < 0.5].mean()


# the data, shuffled and split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
input_dim = 784
epochs = 20

# create training+test positive and negative pairs
digit_indices = [np.where(y_train == i)[0] for i in range(10)]
tr_pairs, tr_y = create_pairs(x_train, digit_indices)

digit_indices = [np.where(y_test == i)[0] for i in range(10)]
te_pairs, te_y = create_pairs(x_test, digit_indices)

# network definition
base_network = create_base_network(input_dim)

input_a = Input(shape=(input_dim,))
input_b = Input(shape=(input_dim,))

# because we re-use the same instance `base_network`,
# the weights of the network
# will be shared across the two branches
processed_a = base_network(input_a)
processed_b = base_network(input_b)

distance = Lambda(euclidean_distance,
                  output_shape=eucl_dist_output_shape)([processed_a, processed_b])
print('proc' + str(processed_a.shape))
print('distance ' + str(distance.shape))
model = Model([input_a, input_b], distance)

# train
rms = RMSprop()
model.compile(loss=contrastive_loss, optimizer=rms)
model.fit([tr_pairs[:, 0], tr_pairs[:, 1]], tr_y,
          batch_size=128,
          epochs=epochs,
          validation_data=([te_pairs[:, 0], te_pairs[:, 1]], te_y))

# compute final accuracy on training and test sets
pred = model.predict([tr_pairs[:, 0], tr_pairs[:, 1]])
tr_acc = compute_accuracy(pred, tr_y)
pred = model.predict([te_pairs[:, 0], te_pairs[:, 1]])
te_acc = compute_accuracy(pred, te_y)

print('* Accuracy on training set: %0.2f%%' % (100 * tr_acc))
print('* Accuracy on test set: %0.2f%%' % (100 * te_acc))

**Comment by phobrain** [comment] 2017-11-13 03:05
That one actually works with plaidml, I too-quickly assumed it was the siamese aspect:

    tensorflow/core/common_runtime/gpu/gpu_device.cc:1055] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
    * Accuracy on training set: 99.96%
    * Accuracy on test set: 99.50%
    real	1m3.182s

    INFO:plaidml:Opening device "geforce_gtx_1080_ti.0"
    * Accuracy on training set: 99.94%
    * Accuracy on test set: 99.55%
    real	1m10.657s

Off to figure a minimal setup for the real prog, is there somewhere I can email a tar file with data?

**Comment by jbruestle** [comment] 2017-11-13 03:25
Sure, you can either upload the data somewhere and put a link here, or you can email
it to info@vertex.ai

**Comment by phobrain** [comment] 2017-11-13 06:53
http://phobrain.com/pr/home/plaidml_sia.tz

**Comment by earhart** [comment] 2017-11-14 00:09
Hi @phobrain - thanks for the bug report!

Could you post a single python file that causes the break you're seeing?  It's not obvious to me from what you've posted, and I'd love to have something I could add to our regression tests.

**Comment by phobrain** [comment] 2017-11-14 00:40
That's a standalone package with a single python file in it: 'tar xzf plaidml_sia.tz' and you will see it. If you want to reproduce some data to run it with, I'll post the file here.

**Comment by earhart** [comment] 2017-11-14 17:56
Awesome -- thanks!  (And sorry for misunderstanding what was in the .tz).  I'm looking into the issue now.

**Comment by earhart** [comment] 2017-11-14 17:58
... hmm, except I don't seem to be able to download it. Could you verify that your web server is running?  (Or just attach the python file to the thread?  I don't think I'll need the data, just the data shape -- I'm not actually trying to train the network.)

**Comment by phobrain** [comment] 2017-11-14 18:01
Try again, just restarted server. 

    On Tuesday, November 14, 2017 9:58 AM, Rob Earhart <notifications@github.com> wrote:
 

 ... hmm, except I don't seem to be able to download it. Could you verify that your web server is running? (Or just attach the python file to the thread? I don't think I'll need the data, just the data shape -- I'm not actually trying to train the network.)—

**Comment by earhart** [comment] 2017-11-14 18:15
Picked it up; thanks again!

**Comment by phobrain** [comment] 2017-11-14 18:21
Now that I think of it, .tz is my own private type abbreviation of .tgz, in honor of the original unix compress utility's .Z suffix. SInce .tz doesn't appear on the OpenOffice list, I hereby claim it in the name of Tanzania!

https://www.openoffice.org/dev_docs/source/file_extensions.html

**Comment by jbruestle** [comment] 2017-11-16 06:58
So we tracked this one down:  It's very interesting.  Short version: you were correct in assuming that the issue was related to the fact that it was a Siamese network, but it's also specific to BatchNorm as well.  In more detail, the batch norm hold a running average of the mean and the variance.  Because the same batch norm was used in both sides of the network, this requires two updates to the running averages in one training batch.  Both these updates try to update the same variable, which is the cause of the error.  Interestingly the autodiff code *does* handle such tied weights, so it's only relevant to non-gradient updates of shared network components.

We've looked into fixing it, but fundementally we would need to have our 'update' mechanism understand more of the semantics of the operation than we currently do, which is a fair amount of plumbing and only relevant in a very small number of use cases.  We did try to only apply one of the updates arbitrarily, but in addition to being a questionable semantic, the network did not train properly.  In the mean time, the workarounds are to not use batch norm in Siamese network, or to have two independent batch norm layers, one for each path.

We are adding a ticket to our internal tracking system to modify the way we handle updates generally, but it will probably be a while before we can get to it.  In the meantime, I'm going to close this ticket so it's not pending indefinitely.  If this is an important feature for you let me know and we can add a public tracking ticket for the actual feature request, but hopefully one of the workarounds will suffice?

**Closed by jbruestle** 2017-11-16 06:58 UTC

**Comment by phobrain** [comment] 2017-11-16 12:20
I wonder if independent batch norms spliced into the middle of the net would break the siamese model? I didn't realize it was possible. Offhand, I'm ready to let it go and work with what I have.

**Comment by MarviB16** [comment] 2020-04-19 17:44
Is there any update to this? I am currently also trying to train a Siamese network with batch normalization, however, I get the same error.

**Comment by phobrain** [comment] 2020-04-20 00:43
Looks like the case was written off. Fwiw I wound up using keras.
