### ISSUE TITLE
facing noise_shape error while using spatial_dropout

### ISSUE THREAD

**Issue by upasana-mittal** [plaidml/plaidml#165] opened 2018-08-29 09:21 UTC
I am facing error on `SpatialDropout1D`. The error I am facing is given below.

 ```
raise PlaidMLKerasException('Unimplemented noise shape in dropout')
 plaidml.keras.backend.PlaidMLKerasException: Unimplemented noise shape in dropout
```

**Comment by Payback80** [comment] 2018-09-22 15:48
i'm facing the same problem too, any workaround?

**Comment by SleepProgger** [comment] 2019-03-04 04:24
Same error here with SpatialDropout2D

```
from keras.layers.core import SpatialDropout2D
from keras.layers.convolutional import Conv2D
from keras.engine.input_layer import Input
x = Input((5,5,3))
x = Conv2D(5, 3)(x)
x = SpatialDropout2D(0.25)(x)
```

->

```
Traceback (most recent call last):
  File "/run/media/nope/data/home/nope/workspace/test/keras_spatial_dropout.py", line 12, in <module>
    x = SpatialDropout2D(0.25)(x)
  File "/home/nope/.local/lib/python3.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/nope/.local/lib/python3.7/site-packages/keras/layers/core.py", line 126, in call
    training=training)
  File "/usr/lib/python3.7/site-packages/plaidml/keras/backend.py", line 753, in in_train_phase
    cx = x()
  File "/home/nope/.local/lib/python3.7/site-packages/keras/layers/core.py", line 124, in dropped_inputs
    seed=self.seed)
  File "/usr/lib/python3.7/site-packages/plaidml/keras/backend.py", line 588, in dropout
    raise PlaidMLKerasException('Unimplemented noise shape in dropout')
plaidml.keras.backend.PlaidMLKerasException: Unimplemented noise shape in dropout
```

Could that layer be supported pretty please ?

**Comment by dgkutnic** [comment] 2019-06-21 20:55
Issues in the `needs info` state for 7+ days will be marked as obsolete and closed. If the issue is still occurring for you, please re-open the issue and provide us with the requested info.

**Closed by dgkutnic** 2019-06-21 20:55 UTC
Labels: needs info, obsolete, verify

**Comment by SleepProgger** [comment] 2019-06-21 23:00
Should be fixed in https://github.com/plaidml/plaidml/pull/305 anyway
