### ISSUE TITLE
"OSError: exception: access violation" while running MobileNet on Intel HD Graphics 5500

### ISSUE THREAD

**Issue by f-rumblefish** [plaidml/plaidml#167] opened 2018-09-03 03:11 UTC
Dear All:

While running MobileNet on Intel HD Graphics 5500, I ran into an access violation problem after 9 epochs.

Here is the setup.

- GPU : Intel HD Graphics 5500
- plaidml : 0.3.5
- plaidml-keras : 0.3.5
- Keras : 2.2.2
- Keras MobileNet fine-tuning by changing the tail to produce 6 classes outputs 

Here is the log.

```
 >>> files =  2528
 >>> x_train.shape =  (2528, 224, 224, 3)
 >>> y_train.shape =  (2528,)
 >>> input_shape =  (224, 224, 3)
 >>> task_type =  1
INFO:plaidml:Opening device "opencl_intel_intel(r)_hd_graphics_5500.0"
D:\pyqt\utility-classification\model_201.py:63: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=input_1 Pl..., outputs=Softmax FL...)`
  model = Model(input = MobileNet_model.input, output = Custom_Output)
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         (None, 224, 224, 3)       0
_________________________________________________________________
conv1_pad (ZeroPadding2D)    (None, 225, 225, 3)       0
_________________________________________________________________
conv1 (Conv2D)               (None, 112, 112, 32)      864
_________________________________________________________________
conv1_bn (BatchNormalization (None, 112, 112, 32)      128
_________________________________________________________________
conv1_relu (ReLU)            (None, 112, 112, 32)      0
_________________________________________________________________
conv_dw_1 (DepthwiseConv2D)  (None, 112, 112, 32)      288
_________________________________________________________________
conv_dw_1_bn (BatchNormaliza (None, 112, 112, 32)      128
_________________________________________________________________
conv_dw_1_relu (ReLU)        (None, 112, 112, 32)      0
_________________________________________________________________
conv_pw_1 (Conv2D)           (None, 112, 112, 64)      2048
_________________________________________________________________
conv_pw_1_bn (BatchNormaliza (None, 112, 112, 64)      256
_________________________________________________________________
conv_pw_1_relu (ReLU)        (None, 112, 112, 64)      0
_________________________________________________________________
conv_pad_2 (ZeroPadding2D)   (None, 113, 113, 64)      0
_________________________________________________________________
conv_dw_2 (DepthwiseConv2D)  (None, 56, 56, 64)        576
_________________________________________________________________
conv_dw_2_bn (BatchNormaliza (None, 56, 56, 64)        256
_________________________________________________________________
conv_dw_2_relu (ReLU)        (None, 56, 56, 64)        0
_________________________________________________________________
conv_pw_2 (Conv2D)           (None, 56, 56, 128)       8192
_________________________________________________________________
conv_pw_2_bn (BatchNormaliza (None, 56, 56, 128)       512
_________________________________________________________________
conv_pw_2_relu (ReLU)        (None, 56, 56, 128)       0
_________________________________________________________________
conv_dw_3 (DepthwiseConv2D)  (None, 56, 56, 128)       1152
_________________________________________________________________
conv_dw_3_bn (BatchNormaliza (None, 56, 56, 128)       512
_________________________________________________________________
conv_dw_3_relu (ReLU)        (None, 56, 56, 128)       0
_________________________________________________________________
conv_pw_3 (Conv2D)           (None, 56, 56, 128)       16384
_________________________________________________________________
conv_pw_3_bn (BatchNormaliza (None, 56, 56, 128)       512
_________________________________________________________________
conv_pw_3_relu (ReLU)        (None, 56, 56, 128)       0
_________________________________________________________________
conv_pad_4 (ZeroPadding2D)   (None, 57, 57, 128)       0
_________________________________________________________________
conv_dw_4 (DepthwiseConv2D)  (None, 28, 28, 128)       1152
_________________________________________________________________
conv_dw_4_bn (BatchNormaliza (None, 28, 28, 128)       512
_________________________________________________________________
conv_dw_4_relu (ReLU)        (None, 28, 28, 128)       0
_________________________________________________________________
conv_pw_4 (Conv2D)           (None, 28, 28, 256)       32768
_________________________________________________________________
conv_pw_4_bn (BatchNormaliza (None, 28, 28, 256)       1024
_________________________________________________________________
conv_pw_4_relu (ReLU)        (None, 28, 28, 256)       0
_________________________________________________________________
conv_dw_5 (DepthwiseConv2D)  (None, 28, 28, 256)       2304
_________________________________________________________________
conv_dw_5_bn (BatchNormaliza (None, 28, 28, 256)       1024
_________________________________________________________________
conv_dw_5_relu (ReLU)        (None, 28, 28, 256)       0
_________________________________________________________________
conv_pw_5 (Conv2D)           (None, 28, 28, 256)       65536
_________________________________________________________________
conv_pw_5_bn (BatchNormaliza (None, 28, 28, 256)       1024
_________________________________________________________________
conv_pw_5_relu (ReLU)        (None, 28, 28, 256)       0
_________________________________________________________________
conv_pad_6 (ZeroPadding2D)   (None, 29, 29, 256)       0
_________________________________________________________________
conv_dw_6 (DepthwiseConv2D)  (None, 14, 14, 256)       2304
_________________________________________________________________
conv_dw_6_bn (BatchNormaliza (None, 14, 14, 256)       1024
_________________________________________________________________
conv_dw_6_relu (ReLU)        (None, 14, 14, 256)       0
_________________________________________________________________
conv_pw_6 (Conv2D)           (None, 14, 14, 512)       131072
_________________________________________________________________
conv_pw_6_bn (BatchNormaliza (None, 14, 14, 512)       2048
_________________________________________________________________
conv_pw_6_relu (ReLU)        (None, 14, 14, 512)       0
_________________________________________________________________
conv_dw_7 (DepthwiseConv2D)  (None, 14, 14, 512)       4608
_________________________________________________________________
conv_dw_7_bn (BatchNormaliza (None, 14, 14, 512)       2048
_________________________________________________________________
conv_dw_7_relu (ReLU)        (None, 14, 14, 512)       0
_________________________________________________________________
conv_pw_7 (Conv2D)           (None, 14, 14, 512)       262144
_________________________________________________________________
conv_pw_7_bn (BatchNormaliza (None, 14, 14, 512)       2048
_________________________________________________________________
conv_pw_7_relu (ReLU)        (None, 14, 14, 512)       0
_________________________________________________________________
conv_dw_8 (DepthwiseConv2D)  (None, 14, 14, 512)       4608
_________________________________________________________________
conv_dw_8_bn (BatchNormaliza (None, 14, 14, 512)       2048
_________________________________________________________________
conv_dw_8_relu (ReLU)        (None, 14, 14, 512)       0
_________________________________________________________________
conv_pw_8 (Conv2D)           (None, 14, 14, 512)       262144
_________________________________________________________________
conv_pw_8_bn (BatchNormaliza (None, 14, 14, 512)       2048
_________________________________________________________________
conv_pw_8_relu (ReLU)        (None, 14, 14, 512)       0
_________________________________________________________________
conv_dw_9 (DepthwiseConv2D)  (None, 14, 14, 512)       4608
_________________________________________________________________
conv_dw_9_bn (BatchNormaliza (None, 14, 14, 512)       2048
_________________________________________________________________
conv_dw_9_relu (ReLU)        (None, 14, 14, 512)       0
_________________________________________________________________
conv_pw_9 (Conv2D)           (None, 14, 14, 512)       262144
_________________________________________________________________
conv_pw_9_bn (BatchNormaliza (None, 14, 14, 512)       2048
_________________________________________________________________
conv_pw_9_relu (ReLU)        (None, 14, 14, 512)       0
_________________________________________________________________
conv_dw_10 (DepthwiseConv2D) (None, 14, 14, 512)       4608
_________________________________________________________________
conv_dw_10_bn (BatchNormaliz (None, 14, 14, 512)       2048
_________________________________________________________________
conv_dw_10_relu (ReLU)       (None, 14, 14, 512)       0
_________________________________________________________________
conv_pw_10 (Conv2D)          (None, 14, 14, 512)       262144
_________________________________________________________________
conv_pw_10_bn (BatchNormaliz (None, 14, 14, 512)       2048
_________________________________________________________________
conv_pw_10_relu (ReLU)       (None, 14, 14, 512)       0
_________________________________________________________________
conv_dw_11 (DepthwiseConv2D) (None, 14, 14, 512)       4608
_________________________________________________________________
conv_dw_11_bn (BatchNormaliz (None, 14, 14, 512)       2048
_________________________________________________________________
conv_dw_11_relu (ReLU)       (None, 14, 14, 512)       0
_________________________________________________________________
conv_pw_11 (Conv2D)          (None, 14, 14, 512)       262144
_________________________________________________________________
conv_pw_11_bn (BatchNormaliz (None, 14, 14, 512)       2048
_________________________________________________________________
conv_pw_11_relu (ReLU)       (None, 14, 14, 512)       0
_________________________________________________________________
conv_pad_12 (ZeroPadding2D)  (None, 15, 15, 512)       0
_________________________________________________________________
conv_dw_12 (DepthwiseConv2D) (None, 7, 7, 512)         4608
_________________________________________________________________
conv_dw_12_bn (BatchNormaliz (None, 7, 7, 512)         2048
_________________________________________________________________
conv_dw_12_relu (ReLU)       (None, 7, 7, 512)         0
_________________________________________________________________
conv_pw_12 (Conv2D)          (None, 7, 7, 1024)        524288
_________________________________________________________________
conv_pw_12_bn (BatchNormaliz (None, 7, 7, 1024)        4096
_________________________________________________________________
conv_pw_12_relu (ReLU)       (None, 7, 7, 1024)        0
_________________________________________________________________
conv_dw_13 (DepthwiseConv2D) (None, 7, 7, 1024)        9216
_________________________________________________________________
conv_dw_13_bn (BatchNormaliz (None, 7, 7, 1024)        4096
_________________________________________________________________
conv_dw_13_relu (ReLU)       (None, 7, 7, 1024)        0
_________________________________________________________________
conv_pw_13 (Conv2D)          (None, 7, 7, 1024)        1048576
_________________________________________________________________
conv_pw_13_bn (BatchNormaliz (None, 7, 7, 1024)        4096
_________________________________________________________________
conv_pw_13_relu (ReLU)       (None, 7, 7, 1024)        0
_________________________________________________________________
global_average_pooling2d_1 ( (None, 1024)              0
_________________________________________________________________
dense_1 (Dense)              (None, 512)               524800
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 3078
=================================================================
Total params: 3,756,742
Trainable params: 3,734,854
Non-trainable params: 21,888
_________________________________________________________________
 >>> CNN Model Training ...

Train on 2275 samples, validate on 253 samples
Epoch 1/15
INFO:plaidml:Analyzing Ops: 809 of 3125 operations complete
INFO:plaidml:Analyzing Ops: 1525 of 3125 operations complete
2272/2275 [============================>.] - ETA: 1s - loss: 0.3761 - acc: 0.8935 INFO:plaidml:Analyzing Ops: 411 of 3125 operations complete
INFO:plaidml:Analyzing Ops: 1038 of 3125 operations complete
INFO:plaidml:Analyzing Ops: 1593 of 3125 operations complete
2275/2275 [==============================] - 1018s 447ms/step - loss: 0.3778 - acc: 0.8927 - val_loss: 0.7065 - val_acc: 0.7945
Epoch 2/15
2275/2275 [==============================] - 1089s 479ms/step - loss: 0.1579 - acc: 0.9538 - val_loss: 3.0231 - val_acc: 0.6047
Epoch 3/15
2275/2275 [==============================] - 1000s 439ms/step - loss: 0.1172 - acc: 0.9684 - val_loss: 0.2483 - val_acc: 0.9170
Epoch 4/15
2275/2275 [==============================] - 1016s 447ms/step - loss: 0.1460 - acc: 0.9600 - val_loss: 0.2790 - val_acc: 0.9289
Epoch 5/15
2275/2275 [==============================] - 997s 438ms/step - loss: 0.0658 - acc: 0.9763 - val_loss: 0.2138 - val_acc: 0.9447
Epoch 6/15
2275/2275 [==============================] - 1016s 447ms/step - loss: 0.0472 - acc: 0.9855 - val_loss: 0.0149 - val_acc: 0.9960
Epoch 7/15
2275/2275 [==============================] - 1074s 472ms/step - loss: 0.1356 - acc: 0.9591 - val_loss: 0.2004 - val_acc: 0.9368
Epoch 8/15
2275/2275 [==============================] - 1016s 446ms/step - loss: 0.0777 - acc: 0.9776 - val_loss: 0.1362 - val_acc: 0.9526
Epoch 9/15
1440/2275 [=================>............] - ETA: 6:05 - loss: 0.0382 - acc: 0.9875Traceback (most recent call last):
  File "model_main_v2.py", line 630, in <module>
    model = model_201.build_and_train(x_train, y_train, 1, num_classes, input_shape)
  File "D:\pyqt\utility-classification\model_201.py", line 95, in build_and_train
    callbacks=[early_stop])
  File "C:\Users\Frank\Anaconda3\envs\plaidenv\lib\site-packages\keras\engine\training.py", line 1037, in fit
    validation_steps=validation_steps)
  File "C:\Users\Frank\Anaconda3\envs\plaidenv\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\Frank\Anaconda3\envs\plaidenv\lib\site-packages\plaidml\keras\backend.py", line 165, in __call__
    self._invoker.invoke()
  File "C:\Users\Frank\Anaconda3\envs\plaidenv\lib\site-packages\plaidml\__init__.py", line 1432, in invoke
    return Invocation(self._ctx, self)
  File "C:\Users\Frank\Anaconda3\envs\plaidenv\lib\site-packages\plaidml\__init__.py", line 1438, in __init__
    self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
```

Any comments or advices? Thanks.

**Comment by f-rumblefish** [comment] 2018-09-09 02:55
I have modified my program and executed it again. The first run completes the task and achive a good result. But, the second run hits the same problem. After five epochs. the program hits the access vilolation problem.

```
Epoch 5/13
  64/2275 [..............................] - ETA: 40:18 - loss: 0.0959 - acc: 0.9688Traceback (most recent call last):
  File "model_main_v3.py", line 572, in <module>
    model = model_201.build_and_train(x_train, y_train, 1, num_classes, input_shape)
  File "D:\pyqt\utility-classification\model_201.py", line 99, in build_and_train
    callbacks=[early_stop])
  File "C:\Users\Frank\Anaconda3\envs\plaidenv\lib\site-packages\keras\engine\training.py", line 1037, in fit
    validation_steps=validation_steps)
  File "C:\Users\Frank\Anaconda3\envs\plaidenv\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\Frank\Anaconda3\envs\plaidenv\lib\site-packages\plaidml\keras\backend.py", line 165, in __call__
    self._invoker.invoke()
  File "C:\Users\Frank\Anaconda3\envs\plaidenv\lib\site-packages\plaidml\__init__.py", line 1432, in invoke
    return Invocation(self._ctx, self)
  File "C:\Users\Frank\Anaconda3\envs\plaidenv\lib\site-packages\plaidml\__init__.py", line 1438, in __init__
    self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
OSError: exception: access violation reading 0x0000003633545FA0
```

**Comment by dgkutnic** [comment] 2019-06-14 18:02
Is this still an issue for you on the newest version of plaidml? If so, can you re-provide us the version information for plaidml, keras, and your HD Graphics drivers, as well as whether the issue occurs deterministically at the same stage of training?

**Comment by dgkutnic** [comment] 2019-06-21 20:41
Issues in the `needs info` state for 7+ days will be marked as obsolete and closed. If the issue is still occurring for you, please re-open the issue and provide us with the requested info.

**Closed by dgkutnic** 2019-06-21 20:41 UTC
Labels: needs info, obsolete
